.github/workflows/test.yaml
test/timer-source/timer-source.feature
test/timer-source/yaks-config.yaml
timer-source.kamelet.yaml

This should setup a CI based on Github actions. I've added the test for the timer-source Kamelet.
We should find a good solution for easily manage credentials before we can test the more complex ones.

chore: add CI configuration

---

aws-kinesis-source.kamelet.yaml
docs/modules/ROOT/pages/aws-kinesis-source.adoc

Moved AWS-Kinesis to AWS2-Kinesis

---

docs/modules/ROOT/pages/http-source.adoc
http-source.kamelet.yaml

This makes it more usable because of https://issues.apache.org/jira/browse/CAMEL-16320

Fix http source to use camel-http

---

aws-s3-source.kamelet.yaml
docs/modules/ROOT/pages/aws-s3-source.adoc
docs/modules/ROOT/pages/dropbox-source.adoc

AWS S3 Source Kamelet: Added autoCreateBucket option with default false

---

aws-sqs-fifo-sink.kamelet.yaml
aws-sqs-sink.kamelet.yaml
aws-sqs-source.kamelet.yaml
docs/modules/ROOT/pages/aws-sqs-fifo-sink.adoc
docs/modules/ROOT/pages/aws-sqs-sink.adoc
docs/modules/ROOT/pages/aws-sqs-source.adoc
docs/modules/ROOT/pages/dropbox-source.adoc

Sqs autocreate queue

---

docs/modules/ROOT/pages/minio-source.adoc
minio-source.kamelet.yaml

Minio Source Kamelet

---

docs/modules/ROOT/pages/kafka-source.adoc
kafka-source.kamelet.yaml

Kafka source authenticated

---

.github/asf-deploy-settings.xml
.github/workflows/asf-snapshots-deploy.yml

Add a gh action for deploying the camel-kamelets catalog and library

---

library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/KameletsCatalog.java
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java

- when a kamelet file cannot be loaded, a log is provided but other
files still can load
- provided a test to ensure that we are not embedding some kamelet files
that are invalid and that we won't detect anymore with existing tests
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Avoid IOException on constructor #225

---

library/camel-kamelets-catalog/src/main/resources/kamelets/openai-completion-action.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/pdf-action.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/rabbitmq-source.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/salesforce-source.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/slack-source.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/ssh-source.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/timer-source.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/webhook-source.kamelet.yaml
openai-completion-action.kamelet.yaml
pdf-action.kamelet.yaml
rabbitmq-source.kamelet.yaml
salesforce-source.kamelet.yaml
slack-source.kamelet.yaml
ssh-source.kamelet.yaml
timer-source.kamelet.yaml
webhook-source.kamelet.yaml

Labels group

---

docs/modules/ROOT/pages/elasticsearch-index-sink.adoc
elasticsearch-index-sink.kamelet.yaml

The ID is auto-generated if coming from kafka and nothing else defined.
Improved docs too.

Adding indexId to ElasticSearch Sink kamelet.

---

docs/modules/ROOT/pages/kafka-source.adoc
kafka-source.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/kafka-source.kamelet.yaml

Kafka Source #247

---

docs/modules/ROOT/pages/elasticsearch-index-sink.adoc
elasticsearch-index-sink.kamelet.yaml

If there is no indexName parameter, try to extract from previous step if previous step is a Kafka source.

feature(es-sink): Make indexName optional.

---

aws-s3-sink.kamelet.yaml
docs/modules/ROOT/pages/aws-s3-sink.adoc
library/camel-kamelets-catalog/src/main/resources/kamelets/aws-s3-sink.kamelet.yaml

If those are needed for minio, we could use the minio kamelet. Or users can create their own Kamelet

AWS S3 Sink Kamelet: removed Override option for URI

---

docs/modules/ROOT/pages/insert-header-action.adoc
insert-header-action.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/insert-header-action.kamelet.yaml

Space in property "name" of insert-header-action cause IllegalArgumentException

---

aws-kinesis-sink.kamelet.yaml
aws-kinesis-source.kamelet.yaml
docs/modules/ROOT/pages/aws-kinesis-sink.adoc
docs/modules/ROOT/pages/aws-kinesis-source.adoc
library/camel-kamelets-catalog/src/main/resources/kamelets/aws-kinesis-sink.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml

AWS Kinesis Kamelets: Region is not capitalized

---

docs/modules/ROOT/pages/jms-amqp-10-sink.adoc
docs/modules/ROOT/pages/jms-amqp-10-source.adoc
jms-amqp-10-sink.kamelet.yaml
jms-amqp-10-source.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/jms-amqp-10-sink.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/jms-amqp-10-source.kamelet.yaml

In some scenarios - outside Camel K - it could prevent the template and
its parameters from being correctly resolved

Fixed invalid connection URL parameter in JMS AMQP Kamelets

---

mongodb-sink.kamelet.yaml

Adding more parameters and expected headers to control document
filtering, sorting, limits, skip, etc

Enhance mongodb sink kamelet

---

aws-kinesis-sink.kamelet.yaml
library/camel-kamelets-catalog/src/main/resources/kamelets/aws-kinesis-sink.kamelet.yaml

Use case when no partition is given was broken

Fix aws-kinesis-sink

---

aws-sqs-source.kamelet.yaml

That kamelet produces the source data, not json

Remove wrong type in aws-sqs-source

---

docs/modules/ROOT/pages/insert-field-action.adoc
insert-field-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/insert-field-action.kamelet.yaml

Related to #463 
Better docs fixes #463

Insert field action doc

---

elasticsearch-index-sink.kamelet.yaml

It is needed by the simple language expressions used.

Added camel:bean dependency to elasticsearch-index-sink.kamelet.yaml

---

docs/modules/ROOT/pages/index.adoc

I have no idea why the previous way of specifying the 'catalog' role/class worked with Asciidoctor 1.5.9 (Antora 2) but specifying the role inside the template works as expected in both Antora 2 and Antora 3.

[Website] Put block role in correct place in template

---

mongodb-source.kamelet.yaml

A Mongodb server can be configured without authentication, for example for testing purposes.

mongodb-source: Changed properties username and password as optional.

---

docs/modules/ROOT/pages/index.adoc

This includes a workaround for a bug or limitation in xref-checker that should be removed when xref-checker is no longer used.
I checked locally that check:xref passes with this change. I can't run deadlinks-linux locally.

[Website] Put block role in correct place in template.

---

mongodb-sink.kamelet.yaml

A Mongodb server can be configured without authentication, for example for testing purposes.

Changed properties username and password as optional.

---

docs/modules/ROOT/pages/google-pubsub-source.adoc
google-pubsub-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/google-pubsub-source.kamelet.yaml

Google Pubsub Source Kamelet 

---

library/camel-kamelets/src/main/resources/kamelets/minio-sink.kamelet.yaml
minio-sink.kamelet.yaml

Fixes #495 Minio Sink Kamelet: The exchangeId as object Name should be set as header and not as property

Minio Sink Kamelet: The exchangeId as object Name should be set as header and not as property

---

rabbitmq-source.kamelet.yaml

Added queue and routingKey as additional optional parameters, adjusted required parameter list.
Removed portNumber since it is not used ir addresses parameter is provided (and it seems we prefer to use the updated url syntax).

Updated rabbitmq-source.kamelet.yaml

---

aws-s3-streaming-upload-sink.kamelet.yaml
docs/modules/ROOT/pages/aws-s3-streaming-upload-sink.adoc
docs/modules/ROOT/pages/has-header-filter-action.adoc
docs/modules/ROOT/pages/kafka-not-secured-source.adoc
docs/modules/ROOT/pages/kafka-source.adoc
docs/modules/ROOT/pages/rabbitmq-source.adoc
docs/modules/ROOT/pages/telegram-source.adoc
library/camel-kamelets/src/main/resources/kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
templates/bindings/camel-k/rabbitmq-source-binding.yaml
templates/bindings/core/rabbitmq-source-binding.yaml

AWS S3 Streaming Upload Kamelet: Support also StreamingUploadTimeout parameter

---

aws-sns-sink.kamelet.yaml
docs/modules/ROOT/pages/aws-sns-sink.adoc
library/camel-kamelets/src/main/resources/kamelets/aws-sns-sink.kamelet.yaml

AWS SNS Subject Header

---

chuck-norris-source.kamelet.yaml

A future extension could add a parameter to re-enable explicite qoutes,
but for now I think it is safer to disable to avoid offending
people when using the source in demos.
Fixes #511.

Exclude explicit quotes for chuck-norris source

---

aws-sqs-batch-sink.kamelet.yaml
aws-sqs-fifo-sink.kamelet.yaml
aws-sqs-sink.kamelet.yaml
aws-sqs-source.kamelet.yaml

These parameter can be very useful for testing purposes.

Added amazonAWSHost and protocol optional parameters to aws-sqs-* kamelets.

---

docs/modules/ROOT/pages/google-sheets-source.adoc
google-sheets-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/google-sheets-source.kamelet.yaml

Google Sheets Source Kamelet: introducing repeatCount optional parameter

---

docs/modules/ROOT/pages/solr-source.adoc
kamelets/solr-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/solr-source.kamelet.yaml

Solr Source Kamelet: Added credentials field

---

kamelets/avro-deserialize-action.kamelet.yaml
kamelets/earthquake-source.kamelet.yaml
kamelets/http-secured-sink.kamelet.yaml
kamelets/http-sink.kamelet.yaml
kamelets/json-deserialize-action.kamelet.yaml
kamelets/openai-classification-action.kamelet.yaml
kamelets/openai-completion-action.kamelet.yaml
kamelets/protobuf-deserialize-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/avro-deserialize-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/earthquake-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/http-secured-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/http-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/json-deserialize-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/openai-classification-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/openai-completion-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/protobuf-deserialize-action.kamelet.yaml

The remove-header-name EIP should use name instead of header-name

---

docs/modules/ROOT/pages/kafka-not-secured-sink.adoc
docs/modules/ROOT/pages/kafka-not-secured-source.adoc
docs/modules/ROOT/pages/kafka-sink.adoc
docs/modules/ROOT/pages/kafka-source.adoc
kamelets/kafka-not-secured-sink.kamelet.yaml
kamelets/kafka-not-secured-source.kamelet.yaml
kamelets/kafka-sink.kamelet.yaml
kamelets/kafka-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/kafka-not-secured-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/kafka-not-secured-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/kafka-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/kafka-source.kamelet.yaml
templates/bindings/camel-k/kafka-not-secured-sink-binding.yaml
templates/bindings/camel-k/kafka-not-secured-source-binding.yaml
templates/bindings/camel-k/kafka-sink-binding.yaml
templates/bindings/camel-k/kafka-source-binding.yaml
templates/bindings/core/kafka-not-secured-sink-binding.yaml
templates/bindings/core/kafka-not-secured-source-binding.yaml
templates/bindings/core/kafka-sink-binding.yaml
templates/bindings/core/kafka-source-binding.yaml

This aligns the not-secured Kafka Kamelets to the standard ones and fixes some documentation.

Rename bootstrap server properties

---

docs/modules/ROOT/pages/aws-cloudwatch-sink.adoc
kamelets/aws-cloudwatch-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-cloudwatch-sink.kamelet.yaml
templates/bindings/camel-k/aws-cloudwatch-sink-binding.yaml
templates/bindings/core/aws-cloudwatch-sink-binding.yaml

Unify the `cw_namespace` from cloudwatch kamelet to use the camelCase. Rename to `cwNamespace`.

Rename cloudwatch cw_namespace property

---

docs/modules/ROOT/pages/cassandra-sink.adoc
docs/modules/ROOT/pages/cassandra-source.adoc
kamelets/cassandra-sink.kamelet.yaml
kamelets/cassandra-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/cassandra-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/cassandra-source.kamelet.yaml
templates/bindings/camel-k/cassandra-sink-binding.yaml
templates/bindings/camel-k/cassandra-source-binding.yaml
templates/bindings/core/cassandra-sink-binding.yaml
templates/bindings/core/cassandra-source-binding.yaml

cassandra-sink:
there is no cql parameter defined
username and password must be optional
preparedStatement was of a wrong type (string but it is actually boolean)
cassandra-source:
username and password must be optional

fix #635: cassandra sink and source kamelets problems

---

pom.xml

Updating Log4j version to 2.17.1 because of CVE-2021-44832 vulnerability.
https://nvd.nist.gov/vuln/detail/CVE-2021-44832

Update Log4j to 2.17.1 to address CVE-2021-44832

---

docs/README_local_build.adoc
docs/antora.yml
docs/local-build.sh
docs/source-map.yml
docs/source-watch.yml

Sets up new docs local-build for camel-kamelets main. See apache/camel-website#731

main update to docs local build v2

---

docs/modules/ROOT/nav.adoc
kamelets/aws-ses-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-ses-sink.kamelet.yaml

AWS SES Sink Kamelet

---

kamelets/extract-field-action.kamelet.yaml
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/ExtractField.java
library/camel-kamelets/src/main/resources/kamelets/extract-field-action.kamelet.yaml

Extract Field Action: Make it possible to set if the extracted field should be in the body or in a particular header

---

kamelets/extract-field-action.kamelet.yaml
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/ExtractField.java
library/camel-kamelets/src/main/resources/kamelets/extract-field-action.kamelet.yaml

Extract Field Action: Add the possibility of setting the header name in case of headerOutput is true

---

kamelets/slack-source.kamelet.yaml

- slack source: add an additional property to control the delay between polls (useful to prevent API throttling)
- slack source: use Gson as json serialization library instead of Jackson as Slack's model rely on Gson annotations

Slack source improvements

---

docs/antora.yml
docs/modules/ROOT/examples/template/kamelet-options.adoc
docs/modules/ROOT/pages/index.adoc

See https://github.com/apache/camel-website/issues/701.
Please check the preview at https://pr-747--camel.netlify.app when ready for completeness and accuracy.

camel-website #710: kamelets RI info (main)

---

kamelets/cassandra-sink.kamelet.yaml
kamelets/cassandra-source.kamelet.yaml

* fix prepareStatements sink parameter
* change default consistency level for source

Fix cassandra kamelets

---

kamelets/aws-s3-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-sink.kamelet.yaml

Support DefaultCredentialProvider in the AWS Kamelets - AWS S3 Sink

---

README.md

Better usage of `template` in the description

Change to flow description

---

kamelets/aws-ddb-streams-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml

Support DefaultCredentialProvider in the AWS Kamelets - AWS DDB Streams

---

kamelets/aws-ec2-sink.kamelet.yaml
kamelets/aws-kinesis-firehose-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-ec2-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-firehose-sink.kamelet.yaml

AWS Kamelets - Support default credentials provider 

---

kamelets/aws-kinesis-sink.kamelet.yaml
kamelets/aws-kinesis-source.kamelet.yaml
kamelets/aws-lambda-sink.kamelet.yaml
kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
kamelets/aws-secrets-manager-sink.kamelet.yaml
kamelets/aws-ses-sink.kamelet.yaml
kamelets/aws-sns-fifo-sink.kamelet.yaml
kamelets/aws-sns-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-lambda-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-secrets-manager-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-ses-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sns-fifo-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sns-sink.kamelet.yaml

Support Default Credentials Provider for AWS Kamelets in 0.7.x

---

kamelets/aws-sqs-batch-sink.kamelet.yaml
kamelets/aws-sqs-fifo-sink.kamelet.yaml
kamelets/aws-sqs-sink.kamelet.yaml
kamelets/aws-sqs-source.kamelet.yaml
kamelets/aws-translate-action.kamelet.yaml
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-batch-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-fifo-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-translate-action.kamelet.yaml

Support Default Credentials Provider for AWS Kamelets

---

jitpack.yml

Use OpenJDK 11 when building with JitPack

---

.github/workflows/yaks-tests.yaml
kamelets/aws-ddb-sink.kamelet.yaml
kamelets/aws-s3-source.kamelet.yaml
library/camel-kamelets-utils/pom.xml
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/aws/ddb/JsonToDdbModelConverter.java
library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/aws/ddb/JsonToDdbModelConverterTest.java
library/camel-kamelets/src/main/resources/kamelets/aws-ddb-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml
test/aws-ddb-sink/amazonDDBClient.groovy
test/aws-ddb-sink/aws-ddb-sink-binding.yaml
test/aws-ddb-sink/aws-ddb-sink-deleteItem.feature
test/aws-ddb-sink/aws-ddb-sink-putItem.feature
test/aws-ddb-sink/aws-ddb-sink-updateItem.feature
test/aws-ddb-sink/putItem.groovy
test/aws-ddb-sink/verifyItems.groovy
test/aws-ddb-sink/yaks-config.yaml
test/earthquake-source/earthquake-source.feature
test/earthquake-source/yaks-config.yaml
test/insert-field-action/insert-field-action-binding.yaml
test/insert-field-action/insert-field-action.feature
test/insert-field-action/yaks-config.yaml
test/mail-sink/mail-sink.feature
test/mail-sink/yaks-config.yaml
test/timer-source/timer-source.feature
test/timer-source/yaks-config.yaml

Add sink Kamelet for AWS DynamoDB
Use YAKS version 0.9.0-202203140033
Add integration test for aws-ddb-sink Kamelet
Introduce unit tests on camel-kamelets-utils module
The Kamelet automatically converts Json body to proper AWS DynamoDB AttributeValue model. The Kamelet uses new utility class org.apache.camel.kamelets.utils.transform.aws.ddb.JsonToDdbModelConverter for this to happen. The PR tests are expected to fail because of this new utility class that is not available in main-SNAPSHOT JitPack repository yet.
Please have a look at the tests running successful on my fork branch where I was using a separate JitPack repository:
https://github.com/christophd/camel-kamelets/pull/3
Also had to refactor YAKS tests in order to stabilize CI workflows:
- Use proper yaks-config conventions
- Use …

Add Kamelet aws-ddb-sink

---

kamelets/aws-cloudwatch-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-cloudwatch-sink.kamelet.yaml

AWS CloudWatch Kamelet: Introduce optional overrideEndpoint and uriEndpointOverride for testing purpose

---

kamelets/aws-sqs-batch-sink.kamelet.yaml
kamelets/aws-sqs-fifo-sink.kamelet.yaml
kamelets/aws-sqs-sink.kamelet.yaml
kamelets/aws-sqs-source.kamelet.yaml
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-batch-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-fifo-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-source.kamelet.yaml

AWS SQS Kamelets: Introduce optional overrideEndpoint and uriEndpointOverride for testing purpose

---

.github/workflows/yaks-tests.yaml

This change in GitHub workflow definition enables PRs to use new/changed utility classes in module camel-kamelets-utils. The workflow overwrites the JitPack dependency coordinates in all Kamelets to point to the actual PR head ref instead of base (e.g. main-SNAPSHOT).
This ensures that the automated tests use the utility classes from that specific PR instead of those from the base branch (e.g. main-SNAPSHOT). So pull request builds are able to have a green GitHub CI workflow even if the base branch is not aware of the utility class before the merge.

chore: Overwrite JitPack dependencies for pull request builds

---

kamelets/xj-template-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/xj-template-action.kamelet.yaml

Use URI notation for some of the parameters we define in actions

---

docs/modules/ROOT/nav.adoc
kamelets/google-bigquery-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/google-bigquery-sink.kamelet.yaml

https://github.com/apache/camel-kamelets/issues/843

Add Google Big Query Sink Kamelet

---

.github/workflows/yaks-tests.yaml
kamelets/kafka-source.kamelet.yaml
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/serialization/kafka/KafkaHeaderDeserializer.java
library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/serialization/kafka/KafkaHeaderDeserializerTest.java
library/camel-kamelets/src/main/resources/kamelets/kafka-source.kamelet.yaml
test/kafka/install.sh
test/kafka/kafka-sink-test.yaml
test/kafka/kafka-sink.feature
test/kafka/kafka-source-test.yaml
test/kafka/kafka-source.feature
test/kafka/uninstall.sh
test/kafka/yaks-config.yaml

- Adds utility class to auto deserialize message headers from byte[] to String
- Option must be explicitly enabled on the source Kamelet
- Add some automated tests on Kafka source/sink Kamelets
This PR uses a new utility class `org.apache.camel.kamelets.utils.serialization.kafka.KafkaHeaderDeserializer` in `kafka-source.kamelet`. The CI tests on this PR are expected to fail because of this until the utility class is available in main_SNAPSHOT.
Please have a look at the PR on my fork to see the successful tests CI workflow: https://github.com/christophd/camel-kamelets/pull/4

chore: Add header deserialize option on Kafka source

---

kamelets/aws-sqs-fifo-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-fifo-sink.kamelet.yaml

aws-sqs-fifo-sink: missing protocol option in the contentBasedDeduplication choice

---

README.md
docs/modules/ROOT/examples/js/kamelets.js
templates/bindings/camel-k/avro-deserialize-action-binding.yaml
templates/bindings/camel-k/avro-serialize-action-binding.yaml
templates/bindings/camel-k/caffeine-action-binding.yaml
templates/bindings/camel-k/has-header-filter-action-binding.yaml
templates/bindings/camel-k/insert-field-action-binding.yaml
templates/bindings/camel-k/protobuf-deserialize-action-binding.yaml
templates/bindings/camel-k/protobuf-serialize-action-binding.yaml
templates/bindings/core/avro-deserialize-action-binding.yaml
templates/bindings/core/avro-serialize-action-binding.yaml
templates/bindings/core/caffeine-action-binding.yaml
templates/bindings/core/has-header-filter-action-binding.yaml
templates/bindings/core/insert-field-action-binding.yaml
templates/bindings/core/protobuf-deserialize-action-binding.yaml
templates/bindings/core/protobuf-serialize-action-binding.yaml

Fix https://github.com/apache/camel-kamelets/issues/866
* There are some generated kamelet bindings are invalid, the auto
generation cannot resolve all the required steps, so there is
a need to create it manually
* Add a comment marker in kamelet binding examples for the auto
generation to skip its creation
* The doc generation source the kamelet binding example file when it
doesn't auto generate the example
* the camel-kamelets directory is hardcoded in kamelets.js as it is
assumed this generation mechanism already assumes this directory

Update non-working examples in Kamelet Catalog docs

---

kamelets/aws-ddb-streams-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml

AWS DDB Streams: IteratorType has been renamed and sequenceNumberProvider is not an option anymore

---

library/camel-kamelets-catalog/pom.xml
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java

Validate the parameters in a Kamelet by looking at catalog

---

kamelets/aws-kinesis-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml

aws-kinesis-source kamelets incompatible with camel 3.16

---

kamelets/jms-ibm-mq-sink.kamelet.yaml
kamelets/jms-ibm-mq-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jms-ibm-mq-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jms-ibm-mq-source.kamelet.yaml
templates/bindings/core/jms-ibm-mq-sink-binding.yaml
templates/bindings/core/jms-ibm-mq-source-binding.yaml

* Currently it uses MQQueueConnectionFactory, which is specific for Queues. It should use MQConnectionFactory, which can be used for queues and topics.
* Add a default property `serverPort: 1414`
* Fix the [yaml dsl routes used in camel 3.15](https://camel.apache.org/manual/camel-3x-upgrade-guide-3_15.html#_camel_yaml_dsl)
Fix https://github.com/apache/camel-kamelets/issues/921

Fix IBM MQ kamelets to use general MQConnectionFactory

---

.github/workflows/yaks-tests.yaml
kamelets/extract-field-action.kamelet.yaml
kamelets/insert-field-action.kamelet.yaml
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/ExtractField.java
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/InsertField.java
library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/ExtractFieldTest.java
library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/InsertFieldTest.java
library/camel-kamelets/src/main/resources/kamelets/extract-field-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/insert-field-action.kamelet.yaml
test/extract-field-action/extract-field-action-binding.yaml
test/extract-field-action/extract-field-action.feature
test/extract-field-action/yaks-config.yaml

extract/insert field action Kamelets throwing nasty Nullpointer exceptions when there is a body provided other than JsonNode.
The PR adds proper error thrown in this situation and also adds some improvements such as
- Add YAKS e2e test for extract field
- Add unit tests on extract/insert field action Kamelets
- Use and set bean properties instead of exchange properties

chore: Avoid NPE on extract/insert field Kamelets

---

kamelets/telegram-sink.kamelet.yaml

If chatId is not provided as parameter on the kamelet binding, camel complains because it tries to use, literally `{{chatId}}` as parameter.

Missing optional in chatId parameter

---

kamelets/ogcapi-features-action.kamelet.yaml

See https://www.ogc.org/standards/ogcapi-features
You can either call for a full geoJSON with all the results or iterate over each result using the `split` parameter.
This is a new geospatial API standard that replaces WFS servers.
Kamelet Binding used to test:
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
name: integration
spec:
source:
ref:
apiVersion: camel.apache.org/v1alpha1
name: timer-source
kind: Kamelet
properties:
period: '5000000'
message: 'NONLD_AREA=0.0&NAME=Croydon'
steps:
- ref:
apiVersion: camel.apache.org/v1alpha1
name: ogcapi-features-action
kind: Kamelet
properties:
collection: activity_level_ldn
url: https://emotional.byteroad.net/
sink:
ref:
apiVersion: camel.apache.org/v1alpha1
name: log-sink
kind: Kamelet
properties:
showAll: true
```

New action that gets features from OGC API server.

---

kamelets/sftp-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/sftp-source.kamelet.yaml

SFTP Kamelet Source: Support ignoreFileNotFoundOrPermissionError parameter

---

docs/modules/ROOT/nav.adoc
kamelets/ceph-sink.kamelet.yaml
kamelets/ceph-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/ceph-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/ceph-source.kamelet.yaml
templates/bindings/camel-k/ceph-sink-binding.yaml
templates/bindings/camel-k/ceph-source-binding.yaml

https://github.com/apache/camel-kamelets/issues/1003

Add Ceph kamelets

---

library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/ReplaceFieldTest.java

More replace field tests

---

kamelets/azure-eventhubs-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-eventhubs-source.kamelet.yaml

Azure Eventhubs Source Kamelet: Return raw data instead of transforming to json

---

kamelets/azure-storage-blob-sink.kamelet.yaml
kamelets/azure-storage-blob-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml

Azure Storage Blob Kamelets should specify which kind of credentials to use

---

kamelets/google-bigquery-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/google-bigquery-sink.kamelet.yaml

Google BigQuery Sink Kamelet: Use ServiceAccountKey parameter instead of forming a connectionFactoryBean

---

kamelets/aws-sqs-source.kamelet.yaml
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-source.kamelet.yaml

AWS SQS Source Kamelet: Add greedy parameter

---

library/camel-kamelets-catalog/pom.xml
library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/KameletsCatalog.java
library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/model/KameletPrefixSchemeEnum.java
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java

I still need to map all the Kamelets prefix to scheme, but this is just a beginning.
Part of #929

Added a Catalog Method showing the supported headers (specific for consumer, producer and common) for a Kamelet

---

library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/model/KameletPrefixSchemeEnum.java
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java

Added a Catalog Method showing the supported headers (specific for consumer, producer and common) for a Kamelet - Azure

---

kamelets/kafka-ssl-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/kafka-ssl-source.kamelet.yaml

Make two-way authentication optional.
Add JAAS config as optional.
Fixes https://github.com/apache/camel-kamelets/issues/1085.

Improve KAFKA SSL source

---

library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/model/KameletPrefixSchemeEnum.java
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java

 Added a Catalog Method showing the supported headers (specific for consumer, producer and common) for a Kamelet

---

kamelets/azure-storage-blob-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml
script/validator/validator.go

Azure Storage Blob Source Kamelet: Add a deleteAfterRead parameter

---

kamelets/log-action.kamelet.yaml
kamelets/log-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/log-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/log-sink.kamelet.yaml

A bit more enhancements on Log Kamelets.

Support more properties for Log Sink/Action Kamelets

---

it-tests/Makefile
it-tests/aws/aws-kinesis/sink/timer-aws-kinesis-it-test.sh
it-tests/aws/aws-kinesis/source/aws-kinesis-log-it-test.sh
it-tests/aws/aws-s3/sink/timer-aws-s3-it-test.sh
it-tests/aws/aws-s3/source/aws-s3-log-it-test.sh
it-tests/aws/aws-sns/sink/terraform/main.tf
it-tests/aws/aws-sns/sink/timer-aws-sns-it-test.sh
it-tests/aws/aws-sns/sink/timer-aws-sns.yaml
it-tests/aws/aws-sqs-fifo/sink/timer-aws-sqs-fifo-it-test.sh
it-tests/aws/aws-sqs/sink/timer-aws-sqs-it-test.sh
it-tests/aws/aws-sqs/source/aws-sqs-log-it-test.sh

IT Tests: Add tests for AWS SNS

---

kamelets/mariadb-source.kamelet.yaml
kamelets/mysql-source.kamelet.yaml
kamelets/postgresql-source.kamelet.yaml
kamelets/sqlserver-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/mariadb-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/mysql-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/postgresql-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/sqlserver-source.kamelet.yaml

Add delay parameter to all SQL Source Kamelets

---

kamelets/ftp-sink.kamelet.yaml
kamelets/ftp-source.kamelet.yaml
kamelets/ftps-sink.kamelet.yaml
kamelets/ftps-source.kamelet.yaml
kamelets/sftp-sink.kamelet.yaml
kamelets/sftp-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/ftp-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/ftp-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/ftps-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/ftps-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/sftp-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/sftp-source.kamelet.yaml

Fixes #1156 for 0.9.x
FTP/FTPS and SFTP

FTP / SFTP connectors missing setting for binary mode transfers 

---

it-tests/Makefile
it-tests/misc/sftp/source/sftp-log-it-test.sh
it-tests/misc/sftp/source/sftp-log.yaml
kamelets/sftp-sink.kamelet.yaml
kamelets/sftp-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/sftp-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/sftp-source.kamelet.yaml
library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java

SFTP / SCP connectors missing authentication options to use a private key

---

kamelets/scp-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/scp-sink.kamelet.yaml

SCP connector missing authentication options to use a private key

---

kamelets/mail-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/mail-sink.kamelet.yaml
test/mail-sink/mail-sink.feature

- In fact mail-sink only supports smtp protocol. Others like pop3 and imap do not make sense for sending mails
- SMTPS protocol is also not supported because SSL context is missing
- to:{{protocol}} stopped working with latest versions so remove protocol property and always use "smtp"
- Also fix YAKS test

Fix mail-sink Kamelet

---

kamelets/fhir-sink.kamelet.yaml

Please consider adding a FHIR sink Kamelet to the catalog.

Add FHIR sink kamelet

---

.github/workflows/yaks-tests.yaml
test/aws-ddb-sink/amazonDDBClient.groovy
test/aws-ddb-sink/yaks-config.yaml
test/aws-s3/amazonS3Client.groovy
test/aws-s3/yaks-config.yaml
test/earthquake-source/earthquake-source.feature
test/earthquake-source/yaks-config.yaml
test/experimental/aws-ddb-sink-exp/amazonDDBClient.groovy
test/experimental/aws-ddb-sink-exp/yaks-config.yaml
test/experimental/aws-s3-exp/amazonS3Client.groovy
test/experimental/aws-s3-exp/yaks-config.yaml
test/extract-field-action/yaks-config.yaml
test/insert-field-action/yaks-config.yaml
test/kafka/install.sh
test/kafka/kafka-sink-binding.yaml
test/kafka/kafka-sink.feature
test/kafka/kafka-source-binding.yaml
test/kafka/kafka-source.feature
test/kafka/uninstall.sh
test/kafka/yaks-config.yaml
test/mail-sink/yaks-config.yaml
test/rest-openapi-sink/yaks-config.yaml
test/salesforce-sink/yaks-config.yaml
test/timer-source/yaks-config.yaml

- Update to YAKS 0.14.1
- Update Camel K to 1.12.0-nightly
- Fix jitpack dependencies used in Kamelets when running GitHub CI jobs for a PR (evaluate current project version e.g. 3.20.0-SNAPSHOT and replace with version from PR)
- Enable integration logger in YAKS tests (better failure analysis when tests fail)
- Fix AWS S3 tests to use path-style access with AWS Java SDK2
- Fix Kafka test to not use *.test.yaml files as these are reserved to be YAML test cases in YAKS
- Do not run experimental tests with each CI job

chore: Fix YAKS tests

---

test/aws-ddb-sink/aws-ddb-sink-deleteItem.feature
test/aws-ddb-sink/aws-ddb-sink-putItem.feature
test/aws-ddb-sink/aws-ddb-sink-updateItem.feature
test/aws-ddb-sink/verifyItems.groovy
test/experimental/aws-ddb-sink-exp/aws-ddb-sink-deleteItem.feature
test/experimental/aws-ddb-sink-exp/aws-ddb-sink-putItem.feature
test/experimental/aws-ddb-sink-exp/aws-ddb-sink-updateItem.feature
test/experimental/aws-ddb-sink-exp/verifyItems.groovy

- Use repeatOnError with maxRetryAttempts instead of static sleep 10sec
- Should give GitHub CI job more time to verify AWS DDB items without increasing the total test execution time

chore: Fix flaky AWS DDB sink YAKS tests

---

kamelets/fhir-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/fhir-source.kamelet.yaml

Convert all the parameters with multiple possible values to enum - Fhir Source

---

kamelets/infinispan-source.kamelet.yaml
kamelets/jolt-transformation-action.kamelet.yaml
kamelets/mongodb-sink.kamelet.yaml
kamelets/pulsar-sink.kamelet.yaml
kamelets/pulsar-source.kamelet.yaml
kamelets/salesforce-source.kamelet.yaml
kamelets/sftp-sink.kamelet.yaml
kamelets/xj-identity-action.kamelet.yaml
kamelets/xj-template-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/infinispan-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jolt-transformation-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/mongodb-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/pulsar-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/pulsar-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/salesforce-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/sftp-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/xj-identity-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/xj-template-action.kamelet.yaml

Convert all the parameters with multiple possible values to enum 

---

kamelets/telegram-sink.kamelet.yaml

See https://github.com/apache/camel-kamelets/issues/981
The consensus was that the documentation wasn't entirely clear as to whether `chatId` was mandatory or not.
It _is_ mandatory but not necessarily as a [Configuration Option](https://camel.apache.org/camel-kamelets/3.20.x/telegram-sink.html#_configuration_options) if provided in the header.

Issue-981: Improve narrative for chatId.

---

kamelets/telegram-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/telegram-sink.kamelet.yaml

Following discussions with @valdar it was felt that including a default value and improving the documentation was the best approach. Keeping the parameter as `required` forces Users to explicitly consider how/where to set the value. Reverting optional behaviour can lead to implicit failures that can be more difficult to diagnose.
@valdar @oscerd WDYT?

Issue-981: Restore optional usage of chatId Configuration Option and correct narrative

---

library/camel-kamelets-catalog/pom.xml
library/camel-kamelets-utils/pom.xml
pom.xml

Use proper Log4j2 binding to support SLF4J 2.x API
The Maven project had both SLF4J API 1.7.x and 2.x in the classpath due to transitive dependencies. Use only SLF4J 2.x API and use proper Log4j2 binding to support 2.x API

chore: Fix Log4j2 to SLF4J2 binding

---

.github/workflows/ci-build.yml
.github/workflows/java-tests.yaml

Prevents deploy build job to fail on forked repositories

chore: Run deploy GitHub workflow job on main repo only

---

kamelets/aws-ddb-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-ddb-sink.kamelet.yaml

See https://github.com/apache/camel-kamelets/issues/1336

Issue-1336: DynamoDB Sink - use enum for available operations

---

kamelets/kafka-not-secured-source.kamelet.yaml
kamelets/kafka-source.kamelet.yaml
kamelets/kafka-ssl-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/kafka-not-secured-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/kafka-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/kafka-ssl-source.kamelet.yaml

Kafka Source Kamelets: Enable deserializeHeaders by default

---

kamelets/azure-storage-blob-changefeed-source.kamelet.yaml
kamelets/azure-storage-blob-sink.kamelet.yaml
kamelets/azure-storage-blob-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-changefeed-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml

Azure Storage Blob Kamelets: Use just the SHARED_ACCOUNT_KEY credentials as default

---

kamelets/azure-storage-blob-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-sink.kamelet.yaml

Azure Storage Blob Sink: Remove operation parameter, since the kamelet has been developed just for uploadBlockBlob operation

---

kamelets/cassandra-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/cassandra-source.kamelet.yaml

Cassandra Kamelets: Consistency Level in source should list only available consistency level for reading

---

docs/modules/ROOT/nav.adoc
kamelets/graphql-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/graphql-sink.kamelet.yaml

Added GraphQL basic sink Kamelet

---

kamelets/oracle-database-sink.kamelet.yaml
kamelets/oracle-database-source.kamelet.yaml

Correct format of URL is given below so replaced // with @
```
url="jdbc:oracle:thin:@(DESCRIPTION=
(LOAD_BALANCE=on)
(ADDRESS_LIST=
(ADDRESS=(PROTOCOL=TCP)(HOST=host1) (PORT=5221))
(ADDRESS=(PROTOCOL=TCP)(HOST=host2)(PORT=5221)))
(CONNECT_DATA=(SERVICE_NAME=orcl)))"
```

 fixed Oracle connection URL

---

kamelets/jms-ibm-mq-sink.kamelet.yaml
kamelets/jms-ibm-mq-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jms-ibm-mq-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jms-ibm-mq-source.kamelet.yaml

This PR adds a sslCipherSuite property to the jms-ibm-mq sink and source kamelets that enables using TLS with IBM MQ.

added sslCipherSuite property so TLS can be enabled

---

kamelets/aws-ddb-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-ddb-sink.kamelet.yaml

Bean: Use properties instead of property with key and value - AWS DDB Sink

---

test/earthquake-source/earthquake-source.feature
test/earthquake-source/earthquake-to-http.yaml
test/earthquake-source/yaks-config.yaml
test/timer-source/timer-to-http.yaml
test/timer-source/yaks-config.yaml

- Use KameletBinding yaml file resource instead of YAKS bind step

chore: Improve YAKS tests

---

infra/aws-s3/Readme.md
infra/aws-s3/ansible/aws-s3.yaml
infra/aws-s3/cloudformation/aws-s3.yaml
infra/aws-s3/terraform/main.tf

Provide some infrastructure as code configuration files for Terraform/Ansible/Cloudformation 

---

kamelets/jira-add-comment-sink.kamelet.yaml
kamelets/jira-add-issue-sink.kamelet.yaml
kamelets/jira-source.kamelet.yaml
kamelets/jira-transition-issue-sink.kamelet.yaml
kamelets/jira-update-issue-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-add-comment-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-add-issue-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-transition-issue-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-update-issue-sink.kamelet.yaml
library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java

- Fix https://github.com/apache/camel-kamelets/issues/1529
- In case the maven plugin fails to a unknown parameter, list all available endpoint parameters

Support personal token authentication to jira

---

kamelets/jira-add-comment-sink.kamelet.yaml
kamelets/jira-add-issue-sink.kamelet.yaml
kamelets/jira-source.kamelet.yaml
kamelets/jira-transition-issue-sink.kamelet.yaml
kamelets/jira-update-issue-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-add-comment-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-add-issue-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-transition-issue-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-update-issue-sink.kamelet.yaml
library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java

- Fix https://github.com/apache/camel-kamelets/issues/1529
- In case the maven plugin fails to a unknown parameter, list all available endpoint parameters
(cherry picked from commit 035cd06d789d978b91574488759447ae591d0a06)

Support personal token authentication to jira (3.20.x)

---

kamelets/jira-add-comment-sink.kamelet.yaml
kamelets/jira-add-issue-sink.kamelet.yaml
kamelets/jira-source.kamelet.yaml
kamelets/jira-transition-issue-sink.kamelet.yaml
kamelets/jira-update-issue-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-add-comment-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-add-issue-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-transition-issue-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jira-update-issue-sink.kamelet.yaml
library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java

- Fix https://github.com/apache/camel-kamelets/issues/1529
- In case the maven plugin fails to a unknown parameter, list all available endpoint parameters
(cherry picked from commit 035cd06d789d978b91574488759447ae591d0a06)

Support personal token authentication to jira (3.x)

---

README.md

it is now git and no more svn, using the generic terminology Source Version Control to limit need to update it in the future

Remove mention to SVN in readme

---

.github/workflows/automatic-changelog-update.yml
.github/workflows/backport.yml
.github/workflows/java-tests.yaml
.github/workflows/main-push-regen.yaml
.github/workflows/validate.yaml

it will avoid this kind of warnings:
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-go@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Update GitHub Action version

---

pom.xml

Use https instead of http for maven metadata information of the

---

script/validator/validator.go

fixes #1577
see also CAMEL-17788

Remove no more needed check on reserved keyword for kamelet

---

.github/workflows/main-push-regen.yaml

the cache for Maven is now built-in with actions/setup-java@v3
it will also avoid warning: `The following actions uses node12 which is
deprecated and will be forced to run on node16: actions/cache@v1 For
more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/`

Remove no more needed GitHub actions/cache

---

kamelets/simple-filter-action.kamelet.yaml

We need to find a way to include  ${} chars which is giving a warning in the website generation.

fix(ci): remove example breaking site

---

.github/workflows/yaks-tests.yaml
test/Makefile
test/README.md
test/avro-data-type/yaks-config.yaml
test/avro-serdes-action/yaks-config.yaml
test/aws-s3/aws-s3-to-http.feature
test/salesforce-sink/salesforce-sink.feature
test/salesforce-sink/yaks-config.yaml

- Adding Makefile as a wrapper for the YAKS binary
- Makes local YAKS test execution more comfortable
- Automatically set YAKS runtime options such as Camel JBang version or local Kamelets directory
- Use the Makefile in GitHub actions CI to run all YAKS tests

Add Makefile to run YAKS tests

---

library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/format/converter/json/JsonStructDataType.java

- Support empty message body value and initialize the application-x-struct data type with empty JsonNode {} value
- Allows follow-up action Kamelets such as insert-field-action to add more fields to the empty JsonNode body
Example:
1. webhook-source creates empty message body
2. application-x-struct data-type used as output data type initializes empty JsonNode
3. insert-field action Kamelet uses header fields to set fields on the JsonNode
4. Json struct gets serialized to String value as outcome

Enhance application-x-struct data type

---

kamelets/insert-field-action.kamelet.yaml
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/InsertField.java
library/camel-kamelets/src/main/resources/kamelets/insert-field-action.kamelet.yaml

- Support simple language parsed value
- Minor typo fix

Enhance insert-field-action.kamelet

---

kamelets/google-sheets-sink.kamelet.yaml
library/camel-kamelets-utils/pom.xml
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/format/converter/google/sheets/CellCoordinate.java
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/format/converter/google/sheets/GoogleSheetsJsonStructDataType.java
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/format/converter/google/sheets/RangeCoordinate.java
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/format/converter/json/Json.java
library/camel-kamelets-utils/src/main/resources/META-INF/services/org/apache/camel/datatype/transformer/google-sheets-application-x-struct
library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/format/converter/google/sheets/GoogleSheetsJsonStructDataTypeTest.java
library/camel-kamelets/src/main/resources/kamelets/google-sheets-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/google-sheets-source.kamelet.yaml

- Add google-sheets-sink Kamelet that updates/appends range cell data to a spreadsheet
- Add GoogleSheetsJsonStructDataType that supports transforming generic JsonNode structs from/to ValueRange object
- Add generic json struct data type support to google-sheets-source Kamelet to transform Google Sheets ValueRange object to pure row/column values
- Adjust google-sheets-source Kamelet to support custom columnNames and majorDimension setting
- Expose data type information on google-sheets-source and -sink Kamelets

fix(#1653): Add Google Sheets Sink Kamelet

---

jitpack.yml

- Use JDK17 for JitPack builds
- Should fix main-SNAPSHOT builds for JitPack

chore: Fix JitPack build for main branch

---

kamelets/aws-s3-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml

Expose maxMessagesPerPoll in AWS S3 Source Kamelet

---

.github/workflows/yaks-tests.yaml
kamelets/aws-s3-sink.kamelet.yaml
kamelets/aws-s3-source.kamelet.yaml
kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
test/Makefile
test/aws-ddb-sink/verifyItems.groovy
test/aws-ddb-sink/yaks-config.yaml
test/aws-s3/amazonS3Client.groovy
test/aws-s3/aws-s3-credentials.properties
test/aws-s3/aws-s3-to-http.yaml
test/aws-s3/aws-s3-to-knative-broker.yaml
test/aws-s3/aws-s3-to-knative-channel.yaml
test/aws-s3/aws-s3-to-log-uri-based.groovy
test/aws-s3/aws-s3-uri-pipe.yaml
test/aws-s3/yaks-config.yaml
test/mail-sink/mail-server.groovy
test/mail-sink/mail-sink.feature
test/mail-sink/timer-to-mail.yaml
test/mail-sink/yaks-config.yaml

[chore: Fix YAKS tests](https://github.com/apache/camel-kamelets/commit/9824072d459a8dd5a8a4d17c07cb04533ccd790d)
- Use 4.2.0-SNAPSHOT version in camel-kamelets-version
- Update to YAKS 0.17.0
- Update to Citrus 4.0.0
[chore: Add forcePathStyle option to aws-s3 Kamelets](https://github.com/apache/camel-kamelets/commit/a9355ddf41e8131090313a021287894705f7dd31)
- Since Apache Camel 4 the aws-s3 component supports to force the path style when accessing buckets on AWS S3
- Path style access is essential when testing with local AWS S3 instances such as LocalStack

chore: Fix YAKS tests for 4.2.0-SNAPSHOT

---

kamelets/log-action.kamelet.yaml
kamelets/log-sink.kamelet.yaml
kamelets/pulsar-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/log-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/log-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/pulsar-sink.kamelet.yaml

Use enum instead of x-descriptors

---

kamelets/kafka-apicurio-registry-not-secured-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/kafka-apicurio-registry-not-secured-source.kamelet.yaml
pom.xml

Kafka Apicurio Registry: Use the Quarkus extension as dependency so the Kamelets will work well in Camel K too

---

kamelets/aws-cloudwatch-sink.kamelet.yaml
kamelets/aws-kinesis-source.kamelet.yaml
kamelets/aws-lambda-sink.kamelet.yaml
kamelets/aws-sns-fifo-sink.kamelet.yaml
kamelets/azure-cosmosdb-source.kamelet.yaml
kamelets/http-secured-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-cloudwatch-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-lambda-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sns-fifo-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-cosmosdb-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/http-secured-source.kamelet.yaml

Kamelets spec errors in v4.2.0

---

kamelets/aws-timestream-query-sink.kamelet.yaml
kamelets/google-sheets-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-timestream-query-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/google-sheets-source.kamelet.yaml

Ref #1814 
Ref #1808 
Some leftover errors on main branch:
```
amel-k-operator-77bf96b5b6-k9xc5 camel-k-operator {"level":"error","ts":"2023-12-21T16:20:42Z","msg":"Error occurred whilst applying bundled kamelet","error":"Kamelet.camel.apache.org \"aws-timestream-query-sink\" is invalid: [spec.definition.properties.useDefaultCredentialsProvider.x-descriptors: Invalid value: \"null\": spec.definition.properties.useDefaultCredentialsProvider.x-descriptors in body must be of type array: \"null\", spec.definition.properties.overrideEndpoint.x-descriptors: Invalid value: \"null\": spec.definition.properties.overrideEndpoint.x-descriptors in body must be of type array: \"null\"]","stacktrace":"github.com/apache/camel-k/v2/pkg/install.KameletCatalog.func1.1\n\tgithub.com/apache/camel-k/v2/pkg/ins …
```

Fix #1808: empty x-descriptors field and dataTypes empty default

---

kamelets/azure-cosmosdb-sink.kamelet.yaml
kamelets/azure-cosmosdb-source.kamelet.yaml
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java
library/camel-kamelets/src/main/resources/kamelets/azure-cosmosdb-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-cosmosdb-source.kamelet.yaml
pom.xml

Azure Kamelets: Reflect changes coming from CAMEL-18590 - Azure CosmosDB 

---

kamelets/azure-eventhubs-sink.kamelet.yaml
kamelets/azure-eventhubs-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-eventhubs-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-eventhubs-source.kamelet.yaml

Azure Kamelets: Reflect changes coming from CAMEL-18590 - Azure Eventhubs 

---

tests/camel-kamelets-itest/pom.xml
tests/camel-kamelets-itest/src/test/java/KameletsYaksIT.java
tests/camel-kamelets-itest/src/test/resources/avro-binary-source-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/avro-serialize-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/aws-s3-to-http.yaml
tests/camel-kamelets-itest/src/test/resources/aws/s3/aws-s3-to-http.feature
tests/camel-kamelets-itest/src/test/resources/citrus-application.properties
tests/camel-kamelets-itest/src/test/resources/cucumber.properties
tests/camel-kamelets-itest/src/test/resources/data-type-action-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/extract-field-action-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/insert-field-action-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/kafka-sink-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/timer-to-http-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/timer-to-http.groovy
tests/camel-kamelets-itest/src/test/resources/timer/timer-source.feature
tests/camel-kamelets-itest/src/test/resources/timer/timer-to-http.feature
tests/camel-kamelets-itest/src/test/resources/timer/yaks-config.yaml

Update Apache Camel runtime to 4.4.0-SNAPSHOT

Fix YAKS tests for 4.4.0-SNAPSHOT

---

kamelets/throttle-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/throttle-action.kamelet.yaml

Reverts apache/camel-kamelets#1848
Related to https://issues.apache.org/jira/browse/CAMEL-20355

Revert "Review Throttle Action"

---

docs/modules/ROOT/nav.adoc
kamelets/spring-rabbitmq-sink.kamelet.yaml
kamelets/spring-rabbitmq-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/spring-rabbitmq-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/spring-rabbitmq-source.kamelet.yaml

Added Spring-RabbitMQ Sink and Source Kamelet

---

kamelets/spring-rabbitmq-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/spring-rabbitmq-sink.kamelet.yaml

Spring RabbitMQ Sink Kamelet: Support autoDeclareProducer as parameter

---

kamelets/azure-cosmosdb-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-cosmosdb-source.kamelet.yaml

Azure CosmosDB Source: Expose Kamelet data type information

---

kamelets/azure-eventhubs-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-eventhubs-source.kamelet.yaml

Azure Eventhubs Source: Expose Kamelet data type information

---

kamelets/aws-ddb-streams-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml

AWS DDB Stream Source: Expose Kamelet data type information

---

kamelets/azure-storage-datalake-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-storage-datalake-source.kamelet.yaml

Azure Storage Datalake Source: Expose Kamelet data type information

---

kamelets/jms-ibm-mq-sink.kamelet.yaml
kamelets/jms-ibm-mq-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jms-ibm-mq-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/jms-ibm-mq-source.kamelet.yaml

The following exception occurs with the current MQConnectionFactory bean:
```
2024-04-26 16:54:59.392  WARN 478114 --- [ #4 - timer://x] camel.component.timer.TimerConsumer : Error processing exchange. Exchange[0EDF2D94283643D-0000000000000000]. Caused by: [java.lang.IllegalArgumentException - connectionFactory must be specified]
java.lang.IllegalArgumentException: connectionFactory must be specified
at org.apache.camel.util.ObjectHelper.notNull(ObjectHelper.java:153) ~[camel-util-4.4.1.jar:4.4.1]
at org.apache.camel.component.jms.JmsConfiguration.createConnectionFactory(JmsConfiguration.java:1744) ~[camel-jms-4.4.1.jar:4.4.1]
```

Replace IBM bean by the IBM jakarta version

---

kamelets/aws-ddb-streams-source.kamelet.yaml
library/camel-kamelets-utils/pom.xml
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/serialization/gson/JavaTimeInstantTypeAdapter.java
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/aws2/ddb/Ddb2JsonStructDataTypeTransformer.java
library/camel-kamelets-utils/src/main/resources/META-INF/services/org/apache/camel/transformer/aws2-ddb-application-x-struct
library/camel-kamelets-utils/src/main/resources/META-INF/services/org/apache/camel/transformer/aws2-ddb-application-x-struct.json
library/camel-kamelets/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml
tests/camel-kamelets-itest/src/test/resources/aws/ddb/amazonDDBClient.groovy
tests/camel-kamelets-itest/src/test/resources/aws/ddb/aws-ddb-sink-deleteItem.feature
tests/camel-kamelets-itest/src/test/resources/aws/ddb/aws-ddb-sink-updateItem.feature
tests/camel-kamelets-itest/src/test/resources/aws/ddb/aws-ddb-source-getItem.feature
tests/camel-kamelets-itest/src/test/resources/aws/ddb/aws-ddb-source-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/aws/ddb/yaks-config.yaml

- Use specific data type transformation to marshal the aws2-ddb record domain model to Json
- Arbitrary Gson marshalling is not able to handle Java time instant type that is being used in aws2-ddb domain model
- Add Java time instant Gson type adapter
- Use Gson with timer instant type adapter in aws2-ddb Json Struct data type transformer
- Add YAKS test to verify aws2-ddb-streams-source Kamelet
AWS DDB Streams source Kamelet raises error during marshal operation. This is due to Gson library not able to handle Java time instant type OOTB. PR introduces a data type transformer in camel-kamelets-utils library to handle Gson marshalling in aws2-ddb-streams-source Kamelet.
Errors raised looked like this:
```
Source                                   ID                             Processor …
```

Fix AWS DDB Streams Source Kamelet

---

kamelets/aws-ddb-streams-source.kamelet.yaml
library/camel-kamelets-utils/pom.xml
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/serialization/gson/JavaTimeInstantTypeAdapter.java
library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/aws2/ddb/Ddb2JsonStructDataTypeTransformer.java
library/camel-kamelets-utils/src/main/resources/META-INF/services/org/apache/camel/transformer/aws2-ddb-application-x-struct
library/camel-kamelets-utils/src/main/resources/META-INF/services/org/apache/camel/transformer/aws2-ddb-application-x-struct.json
library/camel-kamelets/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml
tests/camel-kamelets-itest/src/test/resources/aws/ddb/amazonDDBClient.groovy
tests/camel-kamelets-itest/src/test/resources/aws/ddb/aws-ddb-sink-deleteItem.feature
tests/camel-kamelets-itest/src/test/resources/aws/ddb/aws-ddb-sink-updateItem.feature
tests/camel-kamelets-itest/src/test/resources/aws/ddb/aws-ddb-source-getItem.feature
tests/camel-kamelets-itest/src/test/resources/aws/ddb/aws-ddb-source-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/aws/ddb/yaks-config.yaml
tests/camel-kamelets-itest/src/test/resources/citrus-application.properties

Fix AWS DDB Streams Source Kamelet
- Use specific data type transformation to marshal the aws2-ddb record domain model to Json
- Arbitrary Gson marshalling is not able to handle Java time instant type that is being used in aws2-ddb domain model
- Add Java time instant Gson type adapter
- Use Gson with timer instant type adapter in aws2-ddb Json Struct data type transformer
- Add YAKS test to verify aws2-ddb-streams-source Kamelet
Enable GH actions workflows on 4.4.x branch

[BACKPORT-4.4.x] Fix AWS DDB Streams Source Kamelet

---

library/camel-kamelets-utils/pom.xml

Makes Quarkus runtime properly retrieve the data type transformer implementations (e.g. used in aws-ddb-stream-source Kamelet)

fix(#2032): Add Maven jandex on camel-kamelets-utils module

---

kamelets/google-sheets-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/google-sheets-source.kamelet.yaml

Google Sheets Source: Expose Kamelet data type information

---

kamelets/slack-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/slack-source.kamelet.yaml
tests/camel-kamelets-itest/src/test/resources/avro/README.md
tests/camel-kamelets-itest/src/test/resources/aws/s3/README.md
tests/camel-kamelets-itest/src/test/resources/aws/sqs/README.md
tests/camel-kamelets-itest/src/test/resources/protobuf/README.md
tests/camel-kamelets-itest/src/test/resources/slack/README.md
tests/camel-kamelets-itest/src/test/resources/slack/slack-sink-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/slack/slack-sink.feature
tests/camel-kamelets-itest/src/test/resources/slack/slack-source-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/slack/slack-source.feature
tests/camel-kamelets-itest/src/test/resources/slack/yaks-config.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/README.md

- Add serverUrl property to slack-source.kamelet for better testability reasons
- Use local Slack Http server in tests to verify Slack API calls

chore: Add Slack Kamelets E2E tests

---

kamelets/salesforce-update-sink.kamelet.yaml

Fix https://github.com/apache/camel-kamelets/issues/1590
At runtime the "local-salesforce" bean is renamed which seems to cause the 
NoSuchEndpointException: No endpoint could be found for: local-salesforce-1

Fix salesforce-update-sink.kamelet

---

camel-kamelets-sbom/camel-kamelets-sbom.vex.json

Dear project owners,
We are a group of researchers investigating the usefulness of augmenting Software Bills of Materials (SBOMs) with information about known vulnerabilities of third-party dependencies.
As claimed in previous interview-based studies, a major limitation—according to software practitioners—of existing SBOMs is the lack of information about known vulnerabilities.  For this reason, we would like to investigate how augmented SBOMs are received in open-source projects.
To this aim, we have identified popular open-source repositories on GitHub that provided SBOMs, statically detected vulnerabilities on their dependencies in the OSV database, and, based on its output, we have augmented your repository’s SBOM by leveraging the OpenVEX implementation of the Vulnerability …

add VEX file with vulnerabilities information to SBOM

---

kamelets/spring-rabbitmq-sink.kamelet.yaml
kamelets/spring-rabbitmq-source.kamelet.yaml

Add support for vhost configuration in Spring-RabbitMQ Source/Sink, which was previously added to the deprecated RabbitMQ Source in #1068.
Refs #2114.

Support for RabbitMQ VirtualHost in Spring-RabbitMQ Source/Sink

---

kamelets/aws-eventbridge-sink.kamelet.yaml
kamelets/aws-kinesis-firehose-sink.kamelet.yaml
kamelets/aws-kinesis-sink.kamelet.yaml
kamelets/aws-kinesis-source.kamelet.yaml
kamelets/aws-lambda-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-eventbridge-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-firehose-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-lambda-sink.kamelet.yaml

AWS Kamelets: Support profile and session credentials provider out of the box 

---

kamelets/aws-s3-sink.kamelet.yaml
kamelets/aws-s3-source.kamelet.yaml
kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
kamelets/aws-secrets-manager-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-secrets-manager-sink.kamelet.yaml

AWS Kamelets: Support profile and session credentials provider out of the box

---

.github/workflows/java-tests.yaml

for reference on the security best practice https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Github Actions Security Best practices: Pin Actions to Full lenght Commit SHA - Java Tests Action

---

kamelets/kafka-ssl-sink.kamelet.yaml

Hi,
I was trying to use the Camel's Kafka SSL Sink Connector with a truststore. Of course, truststores usually have a password set, which cannot be configured for this connector. This Pull Request aims to add this configuration option for the underlying Kamelet.
I have already created a PR for the related connector: https://github.com/apache/camel-kafka-connector/pull/1671

Introduce Truststore password configuration

---

kamelets/kafka-ssl-sink.kamelet.yaml

This PR aims to backport https://github.com/apache/camel-kamelets/pull/2202 to the 4.8.X branch, so it can be a part of Camel's connectors 4.8.X LTS release.

[BACKPORT-4.8.x] Introduce Truststore password configuration

---

library/camel-kamelets-catalog/pom.xml
library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java
pom.xml

With this we move the dependency from Camel K CRDs to internal one.

chore(ci): use internal CRDs spec

---

kamelets/mariadb-sink.kamelet.yaml
kamelets/mariadb-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/mariadb-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/mariadb-source.kamelet.yaml

Related to #2278 for MariaDB in 4.8.x

SQL Kamelets: Disable autowiring by default - MariaDB

---

kamelets/aws-redshift-sink.kamelet.yaml
kamelets/aws-redshift-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-redshift-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-redshift-source.kamelet.yaml

Related to #2278 for Redshift on 4.8.x

SQL Kamelets: Disable autowiring by default - AWS Redshift

---

kamelets/google-storage-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/google-storage-source.kamelet.yaml

Add Prefix and Filter parameters to Google Cloud Storage Source Kamelet

---

docs/modules/ROOT/partials/aws-bedrock-agent-runtime-sink-description.adoc
docs/modules/ROOT/partials/aws-bedrock-text-sink-description.adoc
docs/modules/ROOT/partials/aws-cloudtrail-source-description.adoc
docs/modules/ROOT/partials/aws-cloudwatch-sink-description.adoc
kamelets/aws-bedrock-agent-runtime-sink.kamelet.yaml
kamelets/aws-bedrock-text-sink.kamelet.yaml
kamelets/aws-cloudtrail-source.kamelet.yaml
kamelets/aws-cloudwatch-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-bedrock-agent-runtime-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-bedrock-text-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-cloudtrail-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-cloudwatch-sink.kamelet.yaml

Kamelets Catalog - Make the description a one liner 

---

.github/workflows/integration-tests.yaml
pom.xml
tests/camel-kamelets-itest/src/test/java/EndpointAutoConfiguration.java
tests/camel-kamelets-itest/src/test/resources/aws/kinesis/amazonKinesisClient.groovy
tests/camel-kamelets-itest/src/test/resources/aws/s3/amazonS3Client.groovy
tests/camel-kamelets-itest/src/test/resources/aws/s3/aws-s3-to-http.it.yaml
tests/camel-kamelets-itest/src/test/resources/aws/sqs/amazonSQSClient.groovy
tests/camel-kamelets-itest/src/test/resources/citrus-application.properties
tests/camel-kamelets-itest/src/test/resources/earthquake/earthquake-to-http.it.yaml
tests/camel-kamelets-itest/src/test/resources/jira/jira-add-comment-sink-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/jira/jira-add-issue-sink-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/jira/jira-source-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/kafka/kafka-router-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/kafka/kafka-sink-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/kafka/kafka-source-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/openapi/rest-openapi-sink-add-pet.it.yaml
tests/camel-kamelets-itest/src/test/resources/openapi/rest-openapi-sink-delete-pet.it.yaml
tests/camel-kamelets-itest/src/test/resources/slack/slack-sink-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/slack/slack-source-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/timer/timer-to-http-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/timer/timer-to-http.it.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/data-type-action-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/extract-field-action-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/insert-field-action-pipe.it.yaml

- Update to Citrus 4.5.1
- Automatically purge Http server endpoint after each test
- Remove obsolete workaround to create dump output folders in before suite
- Use general Docker registry mirror

chore: Integration test improvements

---

tests/camel-kamelets-itest/src/test/java/EndpointAutoConfiguration.java
tests/camel-kamelets-itest/src/test/resources/aws/s3/aws-s3-to-http.it.yaml
tests/camel-kamelets-itest/src/test/resources/aws/s3/aws-s3-to-http.yaml
tests/camel-kamelets-itest/src/test/resources/citrus-application.properties
tests/camel-kamelets-itest/src/test/resources/earthquake/earthquake-to-http.it.yaml
tests/camel-kamelets-itest/src/test/resources/earthquake/earthquake-to-http.yaml
tests/camel-kamelets-itest/src/test/resources/jira/jira-add-comment-sink-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/jira/jira-add-issue-sink-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/jira/jira-source-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/kafka/kafka-source-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/kafka/kafka-source-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/openapi/rest-openapi-sink-add-pet.it.yaml
tests/camel-kamelets-itest/src/test/resources/openapi/rest-openapi-sink-delete-pet.it.yaml
tests/camel-kamelets-itest/src/test/resources/openapi/rest-openapi-sink-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/slack/application.properties
tests/camel-kamelets-itest/src/test/resources/slack/slack-sink-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/slack/slack-source-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/timer/timer-to-http-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/timer/timer-to-http-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/timer/timer-to-http.it.yaml
tests/camel-kamelets-itest/src/test/resources/timer/timer-to-http.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/data-type-action-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/data-type-action-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/extract-field-action-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/extract-field-action-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/insert-field-action-pipe.it.yaml
tests/camel-kamelets-itest/src/test/resources/transformation/insert-field-action-pipe.yaml

Since Citrus 4.5.2 Camel JBang integrations should be stopped properly on all operating systems so the workaround is not needed anymore
Make tests more stable with separate Http server instances

chore: Improve integration tests

---

docs/modules/ROOT/partials/aws-sqs-sink-description.adoc
docs/modules/ROOT/partials/aws-sqs-source-description.adoc
docs/modules/ROOT/partials/aws-sts-assume-role-action-description.adoc
docs/modules/ROOT/partials/aws-timestream-query-sink-description.adoc
docs/modules/ROOT/partials/aws-translate-action-description.adoc
docs/modules/ROOT/partials/azure-cosmosdb-sink-description.adoc
kamelets/aws-sqs-sink.kamelet.yaml
kamelets/aws-sqs-source.kamelet.yaml
kamelets/aws-sts-assume-role-action.kamelet.yaml
kamelets/aws-timestream-query-sink.kamelet.yaml
kamelets/aws-translate-action.kamelet.yaml
kamelets/azure-cosmosdb-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sqs-source.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-sts-assume-role-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-timestream-query-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-translate-action.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/azure-cosmosdb-sink.kamelet.yaml

Kamelets Catalog - Make the description a one liner

---

tests/camel-kamelets-itest/src/test/java/KafkaIT.java

- Stop Kafka producer after test
- Avoid endless Kafka connection warning logs

Improve integration tests

---

kamelets/aws-eventbridge-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-eventbridge-sink.kamelet.yaml
tests/camel-kamelets-itest/pom.xml
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/application.properties
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/aws-eventbridge-sink-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/aws-eventbridge-sink.it.yaml
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/aws-sqs-event-listener-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/setupEventBridge.groovy

Users may need to set the AWS EventBridge details via Kamelet properties instead of sending special Http/CloudEvents headers (e.g. in Knative EventMesh).
- Add option to set detailType, eventSource and resourcesArn via Kamelet properties
- Add option to add an eventSource prefix that is added to all events sent to AWS via this Kamelet sink
- Users are still able to overwrite the settings via Http/CloudEvent headers
- Add automated tests for aws-eventbridge-sink

Enhance AWS EventBridge Sink Kamelet

---

kamelets/aws-eventbridge-sink.kamelet.yaml
library/camel-kamelets/src/main/resources/kamelets/aws-eventbridge-sink.kamelet.yaml
tests/camel-kamelets-itest/pom.xml
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/application.properties
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/aws-eventbridge-sink-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/aws-eventbridge-sink.it.yaml
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/aws-sqs-event-listener-pipe.yaml
tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/setupEventBridge.groovy

- Add option to set detailType, eventSource and resourcesArn via Kamelet properties
- Users are still able to overwrite the settings via Http/CloudEvent headers
- Add automated tests for aws-eventbridge-sink

[BACKPORT-4.14.x] Enhance EventBridge Sink Kamelet
