apache/camel-kamelets

docs/modules/ROOT/pages/google-calendar-stream-source.adoc, docs/modules/ROOT/pages/google-mail-stream-source.adoc, docs/modules/ROOT/pages/google-sheets-stream-source.adoc, google-calendar-stream-source.kamelet.yaml, google-mail-stream-source.kamelet.yaml, google-sheets-source.kamelet.yaml
=> Add delay option to google-* kamelet source

kafka-source.kamelet.yaml
=> Kafka source should not marshal to JSON

dropbox-source.kamelet.yaml, earthquake-source.kamelet.yaml
This does not work on 1.3.x, but works on 1.4.x.
Alias will be added in https://issues.apache.org/jira/browse/CAMEL-16490
=> Use to-d instead of tod for compatibility with 1.4

script/release.sh
This marks kamelets for future reference
=> chore(release): add release script

library/camel-kamelets-catalog/pom.xml, library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/KameletsCatalog.java
=> KameletCatalog is empty with a bundled jar

aws-ddb-streams-source.kamelet.yaml, aws-kinesis-firehose-sink.kamelet.yaml, aws-kinesis-sink.kamelet.yaml, aws-kinesis-source.kamelet.yaml, aws-lambda-sink.kamelet.yaml, aws-s3-sink.kamelet.yaml, aws-s3-source.kamelet.yaml, aws-sns-fifo-sink.kamelet.yaml, aws-sns-sink.kamelet.yaml, aws-sqs-batch-sink.kamelet.yaml, aws-sqs-fifo-sink.kamelet.yaml, aws-sqs-sink.kamelet.yaml, aws-sqs-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-kinesis-firehose-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-kinesis-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-lambda-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-s3-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-s3-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-sns-fifo-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-sns-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-sqs-batch-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-sqs-fifo-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-sqs-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-sqs-source.kamelet.yaml, library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/ReplaceField.java
=> AWS Kamelet Group Label

bitcoin-source.kamelet.yaml, caffeine-action.kamelet.yaml, cassandra-sink.kamelet.yaml, cassandra-source.kamelet.yaml, dns-dig-action.kamelet.yaml, dns-ip-action.kamelet.yaml, dns-lookup-action.kamelet.yaml, dropbox-sink.kamelet.yaml, dropbox-source.kamelet.yaml, earthquake-source.kamelet.yaml, exec-sink.kamelet.yaml, fhir-source.kamelet.yaml, github-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/bitcoin-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/caffeine-action.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/cassandra-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/cassandra-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/dns-dig-action.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/dns-ip-action.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/dns-lookup-action.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/dropbox-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/dropbox-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/earthquake-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/exec-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/fhir-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/github-source.kamelet.yaml
=> More group labels 

extract-field-action.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/extract-field-action.kamelet.yaml
=> Extract field Action

insert-field-action.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/insert-field-action.kamelet.yaml
=> Insert Field Action updated

library/camel-kamelets-catalog/src/main/resources/kamelets/mask-field-action.kamelet.yaml, mask-field-action.kamelet.yaml
=> Mask Field JsonNode

docs/modules/ROOT/pages/replace-field-action.adoc, library/camel-kamelets-catalog/src/main/resources/kamelets/replace-field-action.kamelet.yaml, replace-field-action.kamelet.yaml
=> Replace field Action JsonNode

library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/KameletsCatalog.java, library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/model/KameletAnnotationsNames.java, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java
=> Add group label methods to Kamelets Catalog

extract-field-action.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/extract-field-action.kamelet.yaml
=> Extract Field update

docs/modules/ROOT/nav.adoc, library/camel-kamelets-catalog/src/main/resources/kamelets/value-to-key-action.kamelet.yaml, value-to-key-action.kamelet.yaml
=> Value to key #261

docs/modules/ROOT/nav.adoc, library/camel-kamelets-catalog/src/main/resources/kamelets/replace-field-action.kamelet.yaml, replace-field-action.kamelet.yaml
=> Replace Field action #261

insert-field-action.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/insert-field-action.kamelet.yaml
=> Insert field Action #261

aws-s3-streaming-upload-sink.kamelet.yaml, docs/modules/ROOT/pages/aws-s3-streaming-upload-sink.adoc, library/camel-kamelets-catalog/src/main/resources/kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
=> S3 Batch Size For Streaming Upload

docs/modules/ROOT/pages/mongodb-source.adoc, library/camel-kamelets-catalog/src/main/resources/kamelets/mongodb-source.kamelet.yaml, mongodb-source.kamelet.yaml
=> MongoDB Source Kamelet Improvements

jms-amqp-10-sink.kamelet.yaml, jms-amqp-10-source.kamelet.yaml, jms-apache-artemis-sink.kamelet.yaml, jms-apache-artemis-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/jms-amqp-10-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/jms-amqp-10-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/jms-apache-artemis-sink.kamelet.yaml, library/camel-kamelets-catalog/src/main/resources/kamelets/jms-apache-artemis-source.kamelet.yaml
We don't actually need that one and we can simplify the JMS Kamelets
=> Stop using kamelet-reify for JMS Kamelets

aws-s3-source.kamelet.yaml, docs/modules/ROOT/pages/aws-s3-source.adoc, library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml
=> AWS S3 Kamelet (source) - fetch only meta-data

templates/init-template.kamelet.yaml.vm, templates/init-template.properties
Asking for some initial feedback for a new feature for Camel JBang. 
I'm working on the ability to generate Kamelets from templates. The idea is to make it easier for user to bootstrap their own kamelets. To do so, it uses the templates on this repository.
=> Added Velocity-based templates for the Kamelets

azure-storage-blob-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml
=> Azure storage blob source fix

docs/modules/ROOT/pages/index.adoc
This reverts commit 16ffffe4046f1e187254ce6f2b4a6a9db63a243d.
=> Revert "Put block role in correct place in template"

aws-sns-fifo-sink.kamelet.yaml, docs/modules/ROOT/pages/aws-sns-fifo-sink.adoc, library/camel-kamelets/src/main/resources/kamelets/aws-sns-fifo-sink.kamelet.yaml
=> AWS SNS Fifo Subject Support

infinispan-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/infinispan-source.kamelet.yaml
=> Infinispan source Kamelet: Convert resulting headers into consumable headers for knative

jira-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jira-source.kamelet.yaml
=> Jira Source Kamelet: Fix Joda usage

docs/modules/ROOT/kamelet.adoc.tmpl
This PR includes a very minor typo fix to the Kamelets template
Note that I do not have permissions to merge approved PRs
=> mflinn-kamelet-template-minor-fix

docs/modules/ROOT/pages/salesforce-source.adoc, library/camel-kamelets/src/main/resources/kamelets/salesforce-source.kamelet.yaml, salesforce-source.kamelet.yaml
=> Salesforce Source Kamelet: Do not use kamelet-reify anymore

docs/antora.yml
See https://github.com/apache/camel-website/issues/693
=> 0.5.x update versions for publication

docs/modules/ROOT/pages/solr-sink.adoc, kamelets/solr-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/solr-sink.kamelet.yaml
=> Solr Sink Kamelet: Added credentials

kamelets/avro-deserialize-action.kamelet.yaml, kamelets/avro-serialize-action.kamelet.yaml, kamelets/protobuf-deserialize-action.kamelet.yaml, kamelets/protobuf-serialize-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/avro-deserialize-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/avro-serialize-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/protobuf-deserialize-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/protobuf-serialize-action.kamelet.yaml
=> The remove-property EIP should use name instead of property-name

kamelets/elasticsearch-index-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/elasticsearch-index-sink.kamelet.yaml
=> Elasticsearch index sink indexId random generator for null

pom.xml
=> Upgrade Camel-K Extension to version 5.11.0

kamelets/elasticsearch-index-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/elasticsearch-index-sink.kamelet.yaml
=> elasticsearch-index-sink kamelet should allow empty indexId

kamelets/avro-deserialize-action.kamelet.yaml, kamelets/avro-serialize-action.kamelet.yaml, kamelets/extract-field-action.kamelet.yaml, kamelets/hoist-field-action.kamelet.yaml, kamelets/insert-field-action.kamelet.yaml, kamelets/json-deserialize-action.kamelet.yaml, kamelets/json-serialize-action.kamelet.yaml, kamelets/mask-field-action.kamelet.yaml, kamelets/message-timestamp-router-action.kamelet.yaml, kamelets/openai-classification-action.kamelet.yaml, kamelets/protobuf-deserialize-action.kamelet.yaml, kamelets/protobuf-serialize-action.kamelet.yaml, kamelets/replace-field-action.kamelet.yaml, kamelets/value-to-key-action.kamelet.yaml
=> [json-serialize-action] Unsupported field: unmarshalTypeName

docs/README_local_build.adoc, docs/local-build.sh, docs/source-map.yml, docs/source-watch.yml
Sets up new docs local-build for camel-kamelets 0.6.x. See apache/camel-website#731
=> 0.6.x local build v2

docs/README_local_build.adoc, docs/local-build.sh, docs/source-map.yml, docs/source-watch.yml
Sets up new docs local-build for camel-kamelets 0.5.x. See apache/camel-website#731
=> 0.5.x local build v2

library/camel-kamelets-bom/pom.xml, pom.xml, script/version/UpdateDepsVersionKamelets.groovy
=> Create a Camel-Kamelets BOM

kamelets/aws-redshift-sink.kamelet.yaml, kamelets/aws-redshift-source.kamelet.yaml, kamelets/mariadb-sink.kamelet.yaml, kamelets/mariadb-source.kamelet.yaml, kamelets/mysql-sink.kamelet.yaml, kamelets/mysql-source.kamelet.yaml, kamelets/postgresql-sink.kamelet.yaml, kamelets/postgresql-source.kamelet.yaml, kamelets/sqlserver-sink.kamelet.yaml, kamelets/sqlserver-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-redshift-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-redshift-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mariadb-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mariadb-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mysql-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mysql-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/postgresql-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/postgresql-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-source.kamelet.yaml, pom.xml
=> Bump Commons-dbcp2 to 2.9.0

kamelets/insert-header-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/insert-header-action.kamelet.yaml
=> Insert Header Action: Use Simple as default and not constant for the value parameter binding

kamelets/insert-field-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/insert-field-action.kamelet.yaml
=> Insert Field Action: Use Simple as default and not constant for the value parameter binding

kamelets/extract-field-action.kamelet.yaml, library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/ExtractField.java, library/camel-kamelets/src/main/resources/kamelets/extract-field-action.kamelet.yaml
=> Extract Field Action: Sanitize/check the header name if set and avoid clashes

docs/modules/ROOT/examples/template/kamelet-options.adoc
FYI @djencks I guess you meant this.
=> Camel-Kamelets 0.6.x point to tag v0.6.0

kamelets/replace-field-action.kamelet.yaml, library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/ReplaceField.java, library/camel-kamelets/src/main/resources/kamelets/replace-field-action.kamelet.yaml
=> Replace-field-action disabled and enabled are mandatory

docs/modules/ROOT/nav.adoc, kamelets/drop-header-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/drop-header-action.kamelet.yaml
=> Drop header Kamelet Action

docs/modules/ROOT/nav.adoc, kamelets/drop-headers-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/drop-headers-action.kamelet.yaml
=> Drop headers Kamelet action

docs/antora.yml, docs/modules/ROOT/examples/template/kamelet-options.adoc, docs/modules/ROOT/pages/index.adoc
See apache/camel-website#701.
Please check the preview at https://pr-747--camel.netlify.app when ready for completeness and accuracy.
=> camel-website #710: kamelets RI info (0.6.x)

docs/antora.yml, docs/modules/ROOT/examples/template/kamelet-options.adoc, docs/modules/ROOT/pages/index.adoc
See apache/camel-website#701.
Please check the preview at https://pr-747--camel.netlify.app when ready for completeness and accuracy.
=> camel-website #710: kamelets RI info (0.5.x)

docs/modules/ROOT/examples/js/kamelets.js, docs/modules/ROOT/pages/index.adoc
=> camel-website #701 camel-kamelets RI table setup (main)

docs/antora.yml, docs/modules/ROOT/examples/js/kamelets.js, docs/modules/ROOT/pages/index.adoc
=> camel-website #701 camel-kamelets RI table setup (0.7.x)

docs/antora.yml, docs/modules/ROOT/examples/js/kamelets.js, docs/modules/ROOT/pages/index.adoc
=> camel-website #701 camel-kamelets RI table setup (0.6.x)

docs/antora.yml, docs/modules/ROOT/examples/js/kamelets.js, docs/modules/ROOT/pages/index.adoc
=> camel-website #701 camel-kamelets RI table setup (0.5.x)

kamelets/has-header-filter-action.kamelet.yaml, kamelets/insert-header-action.kamelet.yaml
=> doc-update-header-actions-try2

kamelets/aws-s3-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml
=> Support DefaultCredentialProvider in the AWS Kamelets - AWS S3 Source

.github/workflows/backport.yml, .gitmodules
=> Backport GH Action

kamelets/aws-s3-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-sink.kamelet.yaml
=> Support DefaultCredentialProvider in the AWS Kamelets - AWS S3 Sink

kamelets/aws-ec2-sink.kamelet.yaml, kamelets/aws-kinesis-firehose-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ec2-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-firehose-sink.kamelet.yaml
=> AWS kamelets - Support default credentials provider

kamelets/aws-kinesis-sink.kamelet.yaml, kamelets/aws-kinesis-source.kamelet.yaml, kamelets/aws-lambda-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-lambda-sink.kamelet.yaml
=> Support default credentials provider in AWS Kamelets

kamelets/aws-kinesis-sink.kamelet.yaml, kamelets/aws-kinesis-source.kamelet.yaml, kamelets/aws-lambda-sink.kamelet.yaml, kamelets/aws-s3-streaming-upload-sink.kamelet.yaml, kamelets/aws-secrets-manager-sink.kamelet.yaml, kamelets/aws-ses-sink.kamelet.yaml, kamelets/aws-sns-fifo-sink.kamelet.yaml, kamelets/aws-sns-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-lambda-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-streaming-upload-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-secrets-manager-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ses-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sns-fifo-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sns-sink.kamelet.yaml
=> Support default credentials provider for AWS Kamelets

library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/kafka/ManualCommit.java, pom.xml
=> Update to Camel 3.15.0

pom.xml
=> Upgrade Camel-K Kubernetes-client model to version 5.12.1

kamelets/jms-apache-artemis-sink.kamelet.yaml, kamelets/jms-apache-artemis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jms-apache-artemis-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jms-apache-artemis-source.kamelet.yaml, pom.xml
=> Upgrade Artemis dependency to 2.20.0

docs/modules/ROOT/nav.adoc, kamelets/jslt-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jslt-action.kamelet.yaml
=> JSLT Kamelet Action

kamelets/elasticsearch-index-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/elasticsearch-index-sink.kamelet.yaml
=> make elasticsearch-index-sink user and password properties optional with "?" syntax

.github/workflows/java-tests.yaml
=> Added Java Tests GH Action on PR

kamelets/aws-kinesis-sink.kamelet.yaml, kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml
=> AWS Kinesis Kamelets improvements

kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml
=> AWS Kinesis Source Kamelet Improvements

docs/modules/ROOT/nav.adoc, kamelets/azure-servicebus-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-servicebus-sink.kamelet.yaml
=> Add Azure Servicebus Sink Kamelet

docs/modules/ROOT/nav.adoc, kamelets/mqtt5-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mqtt5-sink.kamelet.yaml
=> MQTT5 Sink Kamelet

kamelets/aws-s3-sink.kamelet.yaml, kamelets/aws-s3-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml
=> AWS S3 Kamelets: Introduce optional overrideEndpoint and uriEndpointOverride for testing purpose 

kamelets/aws-sns-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sns-sink.kamelet.yaml
=> AWS SNS Kamelet: Introduce optional overrideEndpoint and uriEndpointOverride for testing purpose

kamelets/aws-sns-fifo-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sns-fifo-sink.kamelet.yaml
=> AWS SNS FIFO Kamelet: Introduce optional overrideEndpoint and uriEndpointOverride for testing purpose

kamelets/aws-s3-streaming-upload-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
=> AWS S3 Streaming Upload Kamelet: Introduce optional overrideEndpoint and uriEndpointOverride for testing purpose

docs/modules/ROOT/nav.adoc, kamelets/azure-storage-blob-changefeed-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-changefeed-source.kamelet.yaml
=> Add Azure Storage Blob Changefeed Source Kamelet

kamelets/freemarker-template-action.kamelet.yaml, kamelets/jolt-transformation-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/freemarker-template-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jolt-transformation-action.kamelet.yaml
=> Use URI notation for some of the parameters we define in actions

kamelets/mustache-template-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mustache-template-action.kamelet.yaml
=> Use URI notation for some of the parameters we define in actions 

kamelets/aws-s3-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-sink.kamelet.yaml
=> AWS S3 Sink: Add an optional keyName parameter

kamelets/azure-servicebus-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-servicebus-source.kamelet.yaml
=> Azure Servicebus Souce Kamelet: Add subscriptionName as optional parameter for Topic

kamelets/aws-ddb-streams-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml
=> AWS DynamoDB Streams: Introduce optional overrideEndpoint and uriEndpointOverride for testing purpose

kamelets/aws-kinesis-firehose-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-firehose-sink.kamelet.yaml
=> AWS Kinesis Firehose: Introduce optional overrideEndpoint and uriEndpointOverride for testing purpose

kamelets/aws-ec2-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ec2-sink.kamelet.yaml
=> AWS EC2 Kamelet: Introduce optional overrideEndpoint and uriEndpointOverride for testing purpose

kamelets/jolt-transformation-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jolt-transformation-action.kamelet.yaml
=> Jolt Action: Define transformDSL as parameter

kamelets/jms-apache-activemq-sink.kamelet.yaml, kamelets/jms-apache-activemq-source.kamelet.yaml, library/camel-kamelets-bom/pom.xml, library/camel-kamelets/src/main/resources/kamelets/jms-apache-activemq-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jms-apache-activemq-source.kamelet.yaml, pom.xml
=> Activemq Source and Sink kamelet: Add explicit dependency activemq-http

docs/modules/ROOT/nav.adoc, kamelets/mongodb-changes-stream-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mongodb-changes-stream-source.kamelet.yaml
=> MongoDB Changes Stream Consumer Source Kamelet

library/camel-kamelets-catalog/pom.xml, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java
Partially fix #899 
Still some corner case
=> Validate the parameters in a Kamelet by looking at catalog

library/camel-kamelets-bom/pom.xml, library/camel-kamelets-catalog/pom.xml, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, library/kamelets-maven-plugin/pom.xml, library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java, pom.xml
Related to #913 
First validation example
=> Create a Maven Kamelet Plugin - First commit

kamelets/aws-ddb-streams-source.kamelet.yaml, kamelets/aws-kinesis-source.kamelet.yaml, kamelets/aws-redshift-source.kamelet.yaml, kamelets/aws-s3-source.kamelet.yaml, kamelets/aws-sqs-source.kamelet.yaml, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, library/camel-kamelets/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-redshift-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sqs-source.kamelet.yaml
=> aws-* kamelets: expose delay parameter where possible

pom.xml
=> Upgrade Camel to version 3.17.0

docs/antora.yml, library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/ExtractFieldTest.java, library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/InsertFieldTest.java, library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/aws/ddb/JsonToDdbModelConverterTest.java, pom.xml
=> Upgrade Camel version to 3.18.0

kamelets/mongodb-source.kamelet.yaml
Closes https://github.com/apache/camel-k/issues/3228
=> chore: note on using capped collections

library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/MaskFieldTest.java
=> Added a Mask Field test for Action

library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/HoistFieldTest.java
=> Added HoistField Action Test

library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/ReplaceFieldTest.java
=> Added ReplaceField Test

library/camel-kamelets-utils/src/test/java/org/apache/camel/kamelets/utils/transform/RegexRouterTest.java
=> Added RegexRouter action test

kamelets/aws-s3-streaming-upload-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-streaming-upload-sink.kamelet.yaml
=> AWS S3 Streaming Upload: Remove StreamingUploadMode parameter since it is true by default

kamelets/azure-eventhubs-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-eventhubs-sink.kamelet.yaml
=> Azure Eventhubs Sink - partition parameter

kamelets/minio-source.kamelet.yaml
Signed-off-by: Luca Burgazzoli <lburgazzoli@gmail.com>
=> minio: do not convert source payload to json

kamelets/elasticsearch-search-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/elasticsearch-search-source.kamelet.yaml
=> Elasticsearch-search-source won't let me define basic authentication

kamelets/rabbitmq-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/rabbitmq-source.kamelet.yaml
=> RabbitMQ Source Kamelet: Add a vhost parameter

kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml
=> Duplicate some of headers with a different name - AWS Kinesis Source

kamelets/azure-storage-queue-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-queue-source.kamelet.yaml
=> Duplicate some of headers with a different name - Azure Storage Queue Source

kamelets/azure-storage-blob-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml
=> Switch Azure Storage Blob Source from timer producer style to a pure consumer

kamelets/azure-storage-blob-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml
=> Duplicate some of headers with a different name - Azure Storage Blob Source

library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/KameletsCatalog.java, library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/model/KameletPrefixSchemeEnum.java, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java
=> Added a Catalog Method showing the supported headers (specific for consumer, producer and common) for a Kamelet

library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/model/KameletPrefixSchemeEnum.java, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java
=> Added a Catalog Method showing the supported headers (specific for consumer, producer and common) for a Kamelet 

kamelets/aws-cloudtrail-source.kamelet.yaml, library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/model/KameletPrefixSchemeEnum.java, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, library/camel-kamelets/src/main/resources/kamelets/aws-cloudtrail-source.kamelet.yaml
=> Add AWS CloudTrail Source Kamelet

kamelets/salesforce-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/salesforce-source.kamelet.yaml
=> Salesforce Source Kamelet - Add operationName as parameter with subscribe as default value

kamelets/azure-eventhubs-source.kamelet.yaml, kamelets/google-functions-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-eventhubs-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/google-functions-sink.kamelet.yaml
=> Backport 0.9.2

kamelets/sqlserver-sink.kamelet.yaml, kamelets/sqlserver-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-source.kamelet.yaml
=> SQL Server Sink and Source: with 11.2.0.jre11 there are troubles connecting to SQL Server

kamelets/sqlserver-sink.kamelet.yaml, kamelets/sqlserver-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-source.kamelet.yaml
=> SQL Server Source/Sink: with 11.2.0.jre11 there are troubles connecting to SQL Server

kamelets/azure-storage-blob-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml
=> Azure Storage Blob Source Kamelet: Add a delay parameter

library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml
=> Azure Storage Blob Source Kamelet: Add a deleteAfterRead parameter

kamelets/aws-cloudtrail-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-cloudtrail-source.kamelet.yaml
=> AWS Cloudtrail Source Kamelet: Add an eventsource parameter

kamelets/aws-s3-cdc-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-cdc-source.kamelet.yaml, script/validator/validator.go
=> Create an AWS S3 CDC Source Kamelet

kamelets/aws-s3-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-sink.kamelet.yaml
=> aws-s3-sink kamelet ignores keyName property

pom.xml
=> Upgrade Camel to version 3.18.3

kamelets/nats-sink.kamelet.yaml, kamelets/nats-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/nats-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/nats-source.kamelet.yaml
=> Nats Kamelets: Mark servers as secret parameter since it could contains sensitive data if authenticated

kamelets/log-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/log-sink.kamelet.yaml
=> Add level property to Log Sink (0.9.x)

docs/modules/ROOT/nav.adoc, kamelets/log-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/log-action.kamelet.yaml
Sometimes we might want to insert logging between a source and sink. Let's copy Log Sink as an action.
=> Add Log Action Kamelet

docs/antora.yml
=> Aligned to 0.9.3 and usage for Camel K 1.10.3

kamelets/azure-storage-blob-changefeed-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-changefeed-source.kamelet.yaml
=> Azure Storage Blob Changefeed Source Kamelet: Add CredentialType to parameters

kamelets/mariadb-source.kamelet.yaml, kamelets/mysql-source.kamelet.yaml, kamelets/postgresql-source.kamelet.yaml, kamelets/sqlserver-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mariadb-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mysql-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/postgresql-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-source.kamelet.yaml
=> Add delay parameter to all SQL Source Kamelets - 0.9.x

kamelets/ftp-sink.kamelet.yaml, kamelets/ftp-source.kamelet.yaml, kamelets/ftps-sink.kamelet.yaml, kamelets/ftps-source.kamelet.yaml, kamelets/sftp-sink.kamelet.yaml, kamelets/sftp-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftp-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftp-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftps-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftps-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sftp-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sftp-source.kamelet.yaml
Fixes #1156 
FTP/FTPS and SFTP
=> FTP / SFTP connectors missing setting for binary mode transfers

pom.xml
=> Upgrade Classgraph to version 4.8.151

.github/workflows/yaks-tests.yaml, kamelets/jslt-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jslt-action.kamelet.yaml, test/aws-ddb-sink/aws-ddb-sink-binding.yaml
=> JSLT Action - Fix too many slashes in example of template (0.9.x)

it-tests/Makefile, it-tests/misc/sftp/sink/timer-sftp-it-test.sh, it-tests/misc/sftp/sink/timer-sftp.yaml
=> Added it-test for SFTP Sink

pom.xml
=> Upgrade Jackson to version 2.14.1

it-tests/Makefile, it-tests/azure/azure-storage-blob/sink/terraform/main.tf, it-tests/azure/azure-storage-blob/sink/timer-azure-storage-blob-it-test.sh, it-tests/azure/azure-storage-blob/sink/timer-azure-storage-blob.yaml, it-tests/azure/azure-storage-blob/source/azure-storage-blob-log-it-test.sh
=> Azure Storage Blob Sink Kamelet: Add it-test to Makefile

docs/modules/ROOT/nav.adoc, kamelets/azure-storage-blob-cdc-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-cdc-source.kamelet.yaml, script/validator/validator.go
=> Add an Azure Storage Blob CDC Source Kamelet

pom.xml
=> Upgrade Camel to version 3.18.4

kamelets/google-storage-sink.kamelet.yaml, kamelets/google-storage-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/google-storage-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/google-storage-source.kamelet.yaml
=> Google Storage Source/Sink Kamelet: serviceAccountKey is not required

kamelets/slack-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/slack-source.kamelet.yaml
=> Slack Source Kamelet: Set default delay to 1 minute 

kamelets/slack-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/slack-source.kamelet.yaml
=> Slack Source Kamelet: Set default delay to 1 minute

kamelets/log-action.kamelet.yaml, kamelets/log-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/log-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/log-sink.kamelet.yaml
=> Log sink and log action should show streams by default

kamelets/google-pubsub-sink.kamelet.yaml, kamelets/google-pubsub-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/google-pubsub-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/google-pubsub-source.kamelet.yaml
=> Google pubsub optional service account key

kamelets/azure-storage-blob-changefeed-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-changefeed-source.kamelet.yaml
the connector produce one record per event
the connector produced data are in json format
the connector add additional info as record headers
=> fixed Azure Storage Blob changefeed source connector

.github/asf-deploy-settings.xml, .github/workflows/ci-build.yml
=> Added a Deploy action on push

pom.xml
=> Point to 3.20.0 since it has been released

docs/antora.yml
=> 0.9.4 is used on Camel K 1.10.4

kamelets/cassandra-sink.kamelet.yaml, kamelets/cassandra-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/cassandra-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/cassandra-source.kamelet.yaml, library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java
=> Cassandra Kamelets: add extraTypesCodec parameter 

kamelets/aws-translate-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-translate-action.kamelet.yaml
=> Convert all the parameters with multiple possible values to enum - AWS Translate

kamelets/azure-storage-blob-cdc-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-cdc-source.kamelet.yaml
=> Convert all the parameters with multiple possible values to enum - Azure Storage Blob CDC

kamelets/azure-storage-blob-changefeed-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-changefeed-source.kamelet.yaml
=> Convert all the parameters with multiple possible values to enum - Azure Storage Blob Changefeed

kamelets/azure-storage-blob-sink.kamelet.yaml, kamelets/azure-storage-blob-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml
=> Convert all the parameters with multiple possible values to enum - Azure Storage Blob

kamelets/azure-servicebus-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-servicebus-source.kamelet.yaml
=> Convert all the parameters with multiple possible values to enum - Azure Servicebus Source

kamelets/cassandra-sink.kamelet.yaml, kamelets/cassandra-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/cassandra-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/cassandra-source.kamelet.yaml
=> Convert all the parameters with multiple possible values to enum - Cassandra 

kamelets/fhir-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/fhir-source.kamelet.yaml
=> Convert all the parameters with multiple possible values to enum - Fhir Source

kamelets/ftp-sink.kamelet.yaml, kamelets/ftps-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftp-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftps-sink.kamelet.yaml
=> Convert all the parameters with multiple possible values to enum - FTP/FTPS Source

kamelets/infinispan-source.kamelet.yaml, kamelets/jolt-transformation-action.kamelet.yaml, kamelets/mongodb-sink.kamelet.yaml, kamelets/pulsar-sink.kamelet.yaml, kamelets/pulsar-source.kamelet.yaml, kamelets/salesforce-source.kamelet.yaml, kamelets/sftp-sink.kamelet.yaml, kamelets/xj-identity-action.kamelet.yaml, kamelets/xj-template-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/infinispan-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jolt-transformation-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mongodb-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/pulsar-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/pulsar-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/salesforce-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sftp-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/xj-identity-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/xj-template-action.kamelet.yaml
=> Convert all the parameters with multiple possible values to enum 

camel-kamelets-sbom/camel-kamelets-sbom.json, camel-kamelets-sbom/camel-kamelets-sbom.xml, pom.xml
=> Added SBOM generation to camel-kamelets

.github/workflows/generate-sbom-main.yml
=> Added SBOM generation action

kamelets/telegram-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/telegram-sink.kamelet.yaml
Backport of https://github.com/apache/camel-kamelets/pull/1305 to 3.20.x
=> [3.20.x] Issue-981: Improve narrative for chatId

kamelets/telegram-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/telegram-sink.kamelet.yaml
Backport of https://github.com/apache/camel-kamelets/pull/1305 to 3.x
=> [3.x] Issue-981: Improve narrative for chatId

kamelets/telegram-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/telegram-sink.kamelet.yaml
Back port of https://github.com/apache/camel-kamelets/pull/1318
=> [3.x] Issue-981: Restore required setting for chatId and made documentation clearer

kamelets/telegram-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/telegram-sink.kamelet.yaml
Backport of https://github.com/apache/camel-kamelets/pull/1318
=> [3.20.x] Issue-981: Restore required setting for chatId and made documentation clearer.

kamelets/kafka-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-not-secured-source.kamelet.yaml
Fixes #1321 for kafka not secured source Kamelet
=> MQ sink does not map headers from Kafka source

library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java, pom.xml
=> Bump to Camel 3.20.2

kamelets/aws-ddb-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ddb-sink.kamelet.yaml
Backport of https://github.com/apache/camel-kamelets/pull/1337
=> [3.x] Issue-1336: DynamoDB Sink - use enum for available operations

kamelets/aws-ddb-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ddb-sink.kamelet.yaml
Backport of https://github.com/apache/camel-kamelets/pull/1337
=> [3.20.x] Issue-1336: DynamoDB Sink - use enum for available operations

kamelets/aws-ddb-experimental-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ddb-experimental-sink.kamelet.yaml
Further to https://github.com/apache/camel-kamelets/pull/1340
Include update for [experimental](https://github.com/apache/camel-kamelets/pull/1337#issuecomment-1453820173) Kamelet too.
=> [3.20.x] Issue-1336: DynamoDB Sink - Update experimental Kamelet too.

kamelets/aws-ddb-experimental-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ddb-experimental-sink.kamelet.yaml
Further to https://github.com/apache/camel-kamelets/pull/1339
Include update for [experimental](https://github.com/apache/camel-kamelets/pull/1337#issuecomment-1453820173) Kamelet too.
=> [3.x] Issue-1336: DynamoDB Sink - Update experimental Kamelet too.

kamelets/sftp-sink.kamelet.yaml, kamelets/sftp-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sftp-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sftp-source.kamelet.yaml
Fixes #1345 
Needs backport to 3.x and 3.20.x
=> SFTP source - it creates a new folder (if doesn't exist) instead of throwing an exception

docs/modules/ROOT/examples/js/kamelets.js
=> Switch examples to use Kafka kamelets

kamelets/aws-s3-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml
=> AWS S3 Source Kamelet: Removing includeBody option

kamelets/jms-amqp-10-sink.kamelet.yaml, kamelets/jms-amqp-10-source.kamelet.yaml, library/camel-kamelets-bom/pom.xml, library/camel-kamelets/src/main/resources/kamelets/jms-amqp-10-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jms-amqp-10-source.kamelet.yaml, pom.xml
Backport from #1378 on `3.20.x`
=> JMS AMQP 1.0 Source/Sink Kamelets: Replace QPID client with camel-amqp 

kamelets/jms-amqp-10-sink.kamelet.yaml, kamelets/jms-amqp-10-source.kamelet.yaml, library/camel-kamelets-bom/pom.xml, library/camel-kamelets/src/main/resources/kamelets/jms-amqp-10-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jms-amqp-10-source.kamelet.yaml, pom.xml
=> JMS AMQP 1.0 Source/Sink Kamelets: Replace QPID client with camel-amqp

kamelets/kafka-not-secured-source.kamelet.yaml, kamelets/kafka-scram-source.kamelet.yaml, kamelets/kafka-source.kamelet.yaml, kamelets/kafka-ssl-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-scram-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-ssl-source.kamelet.yaml
=> Kafka Source Kamelets: Enable deserializeHeaders by default 

docs/modules/ROOT/nav.adoc, kamelets/azure-storage-datalake-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-datalake-sink.kamelet.yaml
=> Add azure data lake gen2 - Sink Kamelet

kamelets/aws-ddb-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ddb-sink.kamelet.yaml
=> AWS DDB Sink Kamelet: Remove WriteCapacity parameter

kamelets/extract-field-action.kamelet.yaml, library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/transform/ExtractField.java, library/camel-kamelets/src/main/resources/kamelets/extract-field-action.kamelet.yaml
=> Extract Field: Add a property to trim the field

kamelets/cassandra-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/cassandra-source.kamelet.yaml
=> Cassandra Kamelets: Consistency Level in source should list only available consistency level for reading

docs/modules/ROOT/nav.adoc, kamelets/set-kafka-key-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/set-kafka-key-action.kamelet.yaml, library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java, script/validator/validator.go
=> Create a Kamelet action for setting a specific kafka key based on a particular header incoming

library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/format/AnnotationDataTypeLoader.java, pom.xml
=> Upgrade Camel to 4.0.0-M3

docs/modules/ROOT/nav.adoc, kamelets/azure-cosmosdb-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-cosmosdb-sink.kamelet.yaml
=> Add Azure CosmosDB Sink Kamelet

kamelets/aws-kinesis-source.kamelet.yaml, kamelets/aws-redshift-sink.kamelet.yaml, kamelets/aws-redshift-source.kamelet.yaml, kamelets/aws-s3-source.kamelet.yaml, kamelets/aws-sqs-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-redshift-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-redshift-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sqs-source.kamelet.yaml
=> Bean: Use properties instead of property with key and value 

kamelets/azure-storage-blob-source.kamelet.yaml, kamelets/azure-storage-queue-source.kamelet.yaml, kamelets/data-type-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-queue-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/data-type-action.kamelet.yaml
=> Bean: Use properties instead of property with key and value

pom.xml
=> Upgrade Camel to version 3.20.5

library/camel-kamelets-catalog/pom.xml, library/camel-kamelets-utils/pom.xml, pom.xml
=> Align jackson version with core camel project

kamelets/ftp-source.kamelet.yaml, kamelets/ftps-source.kamelet.yaml, kamelets/sftp-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftp-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftps-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sftp-source.kamelet.yaml
=> FTP/SFTP/FTPS Source Kamelets: Add Delete option for SFTP

kamelets/ftp-source.kamelet.yaml, kamelets/ftps-source.kamelet.yaml, kamelets/sftp-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftp-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ftps-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sftp-source.kamelet.yaml
=> FTP/SFTP/FTPS Source Kamelets: Add Delete option

pom.xml
=> Upgrade Camel to version 4.0.0-RC1

infra/aws-sqs/Readme.md, infra/aws-sqs/ansible/aws-sqs.yaml, infra/aws-sqs/cloudformation/aws-sqs.yaml, infra/aws-sqs/terraform/main.tf
=> Provide some infrastructure as code configuration files for Terraform/Ansible/Cloudformation - AWS SQS

library/camel-kamelets-catalog/pom.xml, library/camel-kamelets-catalog/src/main/java/org/apache/camel/kamelets/catalog/KameletsCatalog.java, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java, pom.xml
=> Switch from Fabric8 Camel K Extension to Camel K CRDS

pom.xml
it aligns with Camel
https://github.com/apache/camel/blob/792bb5421b3e9b2a7785bc3ba68177b00b341abc/pom.xml#L126C47-L126C52
=> Upgrade maven-assembly-plugin from 3.4.2 to 3.6.0

pom.xml
it aligns with Camel
https://github.com/apache/camel/blob/792bb5421b3e9b2a7785bc3ba68177b00b341abc/pom.xml#L131
=> Upgrade maven-javadoc-plugin from 3.4.0 to 3.5.0

docs/modules/ROOT/nav.adoc, kamelets/opensearch-index-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/opensearch-index-sink.kamelet.yaml
=> Added Opensearch Sink Kamelet

kamelets/azure-storage-datalake-sink.kamelet.yaml, kamelets/azure-storage-datalake-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-datalake-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-datalake-source.kamelet.yaml
=> Azure Datalake still uses camel-kamelets-utils from github notation

kamelets/azure-servicebus-sink.kamelet.yaml, kamelets/azure-servicebus-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-servicebus-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-servicebus-source.kamelet.yaml
=> Add Support for Topic in Servicebus Kamelets

pom.xml
=> Provide SBOM as released artifacts when releasing

pom.xml
=> Upgrade CycloneDX Maven Plugin to version 2.7.9

kamelets/set-body-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/set-body-action.kamelet.yaml
- Kamelet sets the body with a simple language parsed value
Fixes #1636
=> fix(#1636): Add set-body-action Kamelet

kamelets/azure-storage-blob-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-source.kamelet.yaml
=> Azure Storage Blob Source: Expose Kamelet data type information

library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, pom.xml
=> Upgrade to Apache Camel 4.0.1

kamelets/splunk-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/splunk-source.kamelet.yaml
=> Splunk-source kamelet - initEarliestTime is required parameter

kamelets/azure-storage-blob-changefeed-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-changefeed-source.kamelet.yaml
=> Azure Storage Blob Changefeed : remove dependencies not required anymore

kamelets/aws-s3-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/beer-source.kamelet.yaml
=> Expose maxMessagesPerPoll in AWS S3 Source Kamelet

docs/modules/ROOT/nav.adoc, kamelets/kafka-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/kafka/registry/DefaultAzureCredentialWrapper.java, library/camel-kamelets/src/main/resources/kamelets/kafka-azure-schema-registry-source.kamelet.yaml, script/validator/validator.go
=> Create a Specialized Kamelet starting from Kafka Source using Azure Schema Registry - Added Kamelet

docs/modules/ROOT/nav.adoc, kamelets/kafka-apicurio-registry-not-secured-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-apicurio-registry-not-secured-sink.kamelet.yaml
=> Added Kafka Apicurio Registry Sink Kamelet

docs/modules/ROOT/nav.adoc, kamelets/azure-storage-blob-append-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-blob-append-sink.kamelet.yaml
=> Enhance the kamelet azure-storage-blob-sink for append operation and rotate daily

docs/modules/ROOT/nav.adoc, kamelets/kafka-azure-schema-registry-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-azure-schema-registry-sink.kamelet.yaml, script/validator/validator.go
=> Kafka Azure Schema Registry Sink Kamelet

pom.xml
=> Manage Apicurio Dependencies like we are doing with Groovy Maven Plugin

pom.xml
=> Bump Camel-Dependencies to version 4.2.0

.github/workflows/yaks-tests.yaml, test/aws-ddb-sink/yaks-config.yaml, test/aws-s3/yaks-config.yaml, test/mail-sink/yaks-config.yaml
- Fixes workaround due to YAKS dependency resolving issue
=> chore: Update to YAKS 0.17.1

release-utils/scripts/upload-source.sh
=> Publish SBOM in dist/release

kamelets/kafka-ssl-sink.kamelet.yaml, kamelets/kafka-ssl-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-ssl-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-ssl-source.kamelet.yaml
=> Support SSL Endpoint Algorithm in Kafka SSL Kamelets

docs/modules/ROOT/nav.adoc, kamelets/aws-sts-assume-role-action.kamelet.yaml, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, library/camel-kamelets/src/main/resources/kamelets/aws-sts-assume-role-action.kamelet.yaml
=> Add an AWS STS Assume Role Action Kamelet

pom.xml
=> Bump Camel to version 4.0.3

kamelets/salesforce-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/salesforce-source.kamelet.yaml
=> Review OperationName parameter for Salesforce Source Kamelet - 4.0.x

kamelets/salesforce-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/salesforce-source.kamelet.yaml
=> Review OperationName parameter for Salesforce Source Kamelet

kamelets/salesforce-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/salesforce-source.kamelet.yaml
=> Add rawPayload option to Salesforce source connector

kamelets/throttle-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/throttle-action.kamelet.yaml
=> Review Throttle Action

docs/modules/ROOT/nav.adoc, kamelets/kafka-batch-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-source.kamelet.yaml
=> Support Kafka Batch as Kamelet source - Kafka Source as Batch

docs/modules/ROOT/nav.adoc, kamelets/kafka-batch-scram-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-scram-source.kamelet.yaml
=> Support Kafka Batch as Kamelet source - Kafka Scram Source as Batch

docs/modules/ROOT/nav.adoc, kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, script/validator/validator.go
=> Support Kafka Batch as Kamelet source - Kafka Azure Schema Registry Source as batch

kamelets/slack-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/slack-source.kamelet.yaml
=> Slack source should be in natural order

kamelets/azure-servicebus-sink.kamelet.yaml, kamelets/azure-servicebus-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-servicebus-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-servicebus-source.kamelet.yaml
=> Azure Kamelets: Reflect changes coming from CAMEL-18590 - Azure Servicebus

kamelets/azure-storage-datalake-sink.kamelet.yaml, kamelets/azure-storage-datalake-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-datalake-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-datalake-source.kamelet.yaml
=> Azure Kamelets: Reflect changes coming from CAMEL-18590 - Azure Storage Datalake

kamelets/azure-storage-queue-sink.kamelet.yaml, kamelets/azure-storage-queue-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-queue-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-queue-source.kamelet.yaml
=> Azure Kamelets: Reflect changes coming from CAMEL-18590 - Azure Storage Queue 

docs/modules/ROOT/nav.adoc, kamelets/azure-storage-files-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-files-source.kamelet.yaml
=> Added Azure Files Source Kamelet

docs/modules/ROOT/nav.adoc, kamelets/azure-storage-files-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-files-sink.kamelet.yaml
=> Added Azure Files Sink Kamelet

kamelets/azure-storage-queue-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-queue-source.kamelet.yaml
=> Azure Storage Queue Source: Expose Kamelet data type information

kamelets/snowflake-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/snowflake-sink.kamelet.yaml
=> Added Snowflake Sink Kamelet

docs/modules/ROOT/nav.adoc, kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml
=> Added Kafka Batch Apicurio with Keycloak Kamelet

kamelets/kafka-apicurio-registry-not-secured-source.kamelet.yaml, kamelets/kafka-azure-schema-registry-source.kamelet.yaml, kamelets/kafka-batch-apicurio-registry-not-secured-source.kamelet.yaml, kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml, kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, kamelets/kafka-batch-not-secured-source.kamelet.yaml, kamelets/kafka-batch-scram-source.kamelet.yaml, kamelets/kafka-batch-source.kamelet.yaml, kamelets/kafka-batch-ssl-source.kamelet.yaml, kamelets/kafka-not-secured-apicurio-registry-source.kamelet.yaml, kamelets/kafka-not-secured-source.kamelet.yaml, kamelets/kafka-scram-source.kamelet.yaml, kamelets/kafka-source.kamelet.yaml, kamelets/kafka-ssl-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-apicurio-registry-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-apicurio-registry-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-scram-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-ssl-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-not-secured-apicurio-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-scram-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-ssl-source.kamelet.yaml
=> Support topicIsPattern as Kafka Source Kamelets parameter

library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, pom.xml
=> Upgrade to Camel 4.4.1

kamelets/aws-cloudtrail-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-cloudtrail-source.kamelet.yaml
=> AWS Cloudtrail Source: Expose Kamelet data type information

kamelets/slack-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/slack-source.kamelet.yaml
=> Slack Source: Expose Kamelet data type information

kamelets/azure-storage-files-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/azure-storage-files-source.kamelet.yaml
=> Azure Storage Files Source: Expose Kamelet data type information

kamelets/aws-bedrock-text-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-bedrock-text-sink.kamelet.yaml
=> AWS Bedrock Sink Text - Add all the available models for 4.5.0

docs/modules/ROOT/examples/js/kamelets.js
=> Wrong documentation in Kamelet Catalog for sinks

kamelets/jms-ibm-mq-sink.kamelet.yaml, kamelets/jms-ibm-mq-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jms-ibm-mq-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jms-ibm-mq-source.kamelet.yaml
Backport of https://github.com/apache/camel-kamelets/pull/2006
=> [Backport 4.4.x] Replace IBM bean by the IBM jakarta version

pom.xml
=> Upgrade to Camel 4.6.0

kamelets/google-calendar-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/google-calendar-source.kamelet.yaml
=> Google Calendar Source: Expose Kamelet data type information

kamelets/google-mail-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/google-mail-source.kamelet.yaml
=> Google Mail Source: Expose Kamelet data type information

tests/camel-kamelets-itest/src/test/resources/citrus-application.properties, tests/camel-kamelets-itest/src/test/resources/jira/jira-add-comment-sink-pipe.yaml, tests/camel-kamelets-itest/src/test/resources/jira/jira-add-comment-sink.feature, tests/camel-kamelets-itest/src/test/resources/jira/yaks-config.yaml
Use Apache Camel 4.6.0 in tests
=> chore(e2e): Add Jira add comment Kamelet tests

kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml, pom.xml
=> Add Support for Kinesis KCL Consumers to Kinesis Source Kamelet

pom.xml
=> Upgrade Camel to version 4.4.3

kamelets/aws-sqs-source.kamelet.yaml, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, library/camel-kamelets/src/main/resources/kamelets/aws-sqs-source.kamelet.yaml
Extended SQS source Kamelet with
* maxMessagesPerPoll
* waitTimeoutSeconds
* visibilityTimeout
parameters.
=> #2118 Add extend SQS source Kamelet with more parameters

kamelets/aws-cloudtrail-source.kamelet.yaml, kamelets/aws-cloudwatch-sink.kamelet.yaml, kamelets/aws-ddb-sink.kamelet.yaml, kamelets/aws-ddb-streams-source.kamelet.yaml, kamelets/aws-ec2-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-cloudtrail-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-cloudwatch-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ddb-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ddb-streams-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ec2-sink.kamelet.yaml
=> AWS Kamelets: Support profile and session credentials provider out of the box

kamelets/aws-ses-sink.kamelet.yaml, kamelets/aws-sns-fifo-sink.kamelet.yaml, kamelets/aws-sns-sink.kamelet.yaml, kamelets/aws-sqs-batch-sink.kamelet.yaml, kamelets/aws-sqs-fifo-sink.kamelet.yaml, kamelets/aws-sqs-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-ses-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sns-fifo-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sns-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sqs-batch-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sqs-fifo-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sqs-sink.kamelet.yaml
=> AWS Kamelets: Support profile and session credentials provider out of the box 

docs/modules/ROOT/nav.adoc, kamelets/djl-image-to-text-action.kamelet.yaml, library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, library/camel-kamelets-utils/pom.xml, library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/djl/ImageNetUtil.java, library/camel-kamelets/src/main/resources/kamelets/djl-image-to-text-action.kamelet.yaml, pom.xml
Create an action kamelet based on the Camel AI example: https://github.com/megacamelus/camel-ai-examples/tree/main/image-to-text
=> Create an Image-to-Text action kamelet

kamelets/http-secured-sink.kamelet.yaml, kamelets/http-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/http-secured-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/http-secured-source.kamelet.yaml
=> Support OAuth in HTTP Kamelets 

kamelets/salesforce-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/salesforce-source.kamelet.yaml
=> Salesforce Source Kamelet: Add ReplayId as parameter

kamelets/aws-s3-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-s3-source.kamelet.yaml
=> AWS S3 Source Kamelets: Support moveAfterRead parameter

docs/modules/ROOT/pages/development.adoc, docs/modules/ROOT/pages/index.adoc
To be merged after #2203 is merged
=> chore: docs update to include development guides

kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-source.kamelet.yaml, library/kamelets-maven-plugin/src/main/java/org/apache/camel/kamelets/maven/plugin/ValidateKameletsMojo.java
=> Add option for KCL Consumers to make the ConfigsBuilder for metrics of the Scheduler enable/disable

kamelets/kafka-apicurio-registry-not-secured-source.kamelet.yaml
=> Wrong version in kafka-apicurio-registry-not-secured-source.kamelet.yaml

kamelets/postgresql-sink.kamelet.yaml, kamelets/postgresql-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/postgresql-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/postgresql-source.kamelet.yaml
=> SQL Kamelets: Disable autowiring by default - Postgres

kamelets/sqlserver-sink.kamelet.yaml, kamelets/sqlserver-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-source.kamelet.yaml
Related to #2278 for SQLServer
=> SQL Kamelets: Disable autowiring by default - SQLServer

kamelets/sqlserver-sink.kamelet.yaml, kamelets/sqlserver-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sqlserver-source.kamelet.yaml
Related to #2278 for SQL Server and 4.8.x
=> SQL Kamelets: Disable autowiring by default - SQL Server

kamelets/mariadb-sink.kamelet.yaml, kamelets/mariadb-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mariadb-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mariadb-source.kamelet.yaml
=> SQL Kamelets: Disable autowiring by default - MariaDB

kamelets/mysql-sink.kamelet.yaml, kamelets/mysql-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mysql-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mysql-source.kamelet.yaml
=> SQL Kamelets: Disable autowiring by default - MySQL

kamelets/oracle-database-sink.kamelet.yaml, kamelets/oracle-database-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/oracle-database-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/oracle-database-source.kamelet.yaml
=> SQL Kamelets: Disable autowiring by default - Oracle 

kamelets/aws-redshift-sink.kamelet.yaml, kamelets/aws-redshift-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-redshift-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-redshift-source.kamelet.yaml
=> SQL Kamelets: Disable autowiring by default - AWS Redshift

kamelets/snowflake-sink.kamelet.yaml, kamelets/snowflake-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/snowflake-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/snowflake-source.kamelet.yaml
Related to #2278 for Snowflake
=> SQL Kamelets: Disable autowiring by default - Snowflake

kamelets/cassandra-sink.kamelet.yaml, kamelets/cassandra-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/cassandra-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/cassandra-source.kamelet.yaml
=> Cassandra Kamelets: Disable autowiring by default - CQL

kamelets/cassandra-sink.kamelet.yaml, kamelets/cassandra-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/cassandra-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/cassandra-source.kamelet.yaml
Related to #2278 for Cassandra on 4.8.x
=> Cassandra Kamelets: Disable autowiring by default - CQL Source

pom.xml
=> Upgrade to Camel 4.9.0

library/camel-kamelets-crds/pom.xml
Reverts apache/camel-kamelets#2305
=> Revert "Bump fabric8-version from 6.13.4 to 7.0.0"

kamelets/aws-sqs-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-sqs-source.kamelet.yaml
=> The Kamelet "aws-sqs-source" is invalid

kamelets/kafka-ssl-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-ssl-source.kamelet.yaml
Reverts apache/camel-kamelets#2339
=> Revert "Kafka SSL Source Kamelet - include missing sslTruststorePassword"

docs/modules/ROOT/partials/aws-eventbridge-sink-description.adoc, docs/modules/ROOT/partials/aws-kinesis-firehose-sink-description.adoc, kamelets/aws-eventbridge-sink.kamelet.yaml, kamelets/aws-kinesis-firehose-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-eventbridge-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-firehose-sink.kamelet.yaml
=> Kamelets Catalog - Make the description a one liner 

pom.xml
=> Upgrade to Camel 4.8.3

docs/modules/ROOT/partials/aws-kinesis-sink-description.adoc, kamelets/aws-kinesis-sink.kamelet.yaml, kamelets/aws-kinesis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/aws-kinesis-sink.kamelet.yaml
=> Kamelets Catalog - Make the description a one liner

library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, pom.xml
=> Prepare for 4.10.0 Release: Upgrade to 4.10.0-SNAPSHOT

kamelets/kafka-azure-schema-registry-sink.kamelet.yaml, kamelets/kafka-azure-schema-registry-source.kamelet.yaml, kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-azure-schema-registry-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, pom.xml
=> Align Azure SDK BOM Dependencies with Camel 4.10.0

kamelets/kafka-batch-apicurio-registry-not-secured-source.kamelet.yaml, kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml, kamelets/kafka-not-secured-apicurio-registry-source.kamelet.yaml, kamelets/snowflake-sink.kamelet.yaml, kamelets/snowflake-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-apicurio-registry-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-not-secured-apicurio-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/snowflake-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/snowflake-source.kamelet.yaml, pom.xml
=> Align Dependencies with Camel 4.10.0

pom.xml
=> Upgrade to Camel 4.10.0

kamelets/kafka-batch-apicurio-registry-not-secured-source.kamelet.yaml, kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml, kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, kamelets/kafka-batch-not-secured-source.kamelet.yaml, kamelets/kafka-batch-scram-source.kamelet.yaml, kamelets/kafka-batch-source.kamelet.yaml, kamelets/kafka-batch-ssl-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-apicurio-registry-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-scram-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-ssl-source.kamelet.yaml
=> Kafka Batch Source: Reflect changes from CAMEL-21691

docs/modules/ROOT/pages/index.adoc
=> chore(doc): remove references from other projects

pom.xml
=> Upgrade to Camel 4.8.4

kamelets/kafka-batch-manual-commit-action.kamelet.yaml, kamelets/kafka-manual-commit-action.kamelet.yaml
=> Reflect changes in CAMEL-21833 for Manual Commit in Kafka Kamelets

kamelets/mongodb-changes-stream-source.kamelet.yaml, kamelets/mongodb-sink.kamelet.yaml, kamelets/mongodb-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mongodb-changes-stream-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mongodb-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mongodb-source.kamelet.yaml
=> Reflect changes from CAMEL-21843 in involved Kamelets - MongoDB

kamelets/drop-field-action.kamelet.yaml, kamelets/extract-field-action.kamelet.yaml, kamelets/hoist-field-action.kamelet.yaml, kamelets/insert-field-action.kamelet.yaml, kamelets/mask-field-action.kamelet.yaml, kamelets/message-timestamp-router-action.kamelet.yaml, kamelets/regex-router-action.kamelet.yaml, kamelets/replace-field-action.kamelet.yaml, kamelets/timestamp-router-action.kamelet.yaml, kamelets/value-to-key-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/drop-field-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/extract-field-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/hoist-field-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/insert-field-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mask-field-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/message-timestamp-router-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/regex-router-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/replace-field-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/timestamp-router-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/value-to-key-action.kamelet.yaml
=> Reflect changes from CAMEL-21843 in involved Kamelets - Kafka 

.gitignore
Add the output of the maven build metadata plugin to the gitignore file
=> Add the output of the maven build metadata plugin to the gitignore file

docs/modules/ROOT/nav.adoc, kamelets/solr-sink.kamelet.yaml, kamelets/solr-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/solr-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/solr-source.kamelet.yaml
=> Re-introduce Solr Kamelets

pom.xml
=> Upgrade to Camel 4.11.0

docs/modules/ROOT/nav.adoc, kamelets/pqc-signature-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/pqc-signature-sink.kamelet.yaml
=> Support PQC Component producer operation - Signature operations

kamelets/jms-pooled-apache-artemis-sink.kamelet.yaml, kamelets/jms-pooled-apache-artemis-source.kamelet.yaml, kamelets/kafka-batch-apicurio-registry-not-secured-source.kamelet.yaml, kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml, kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, kamelets/kafka-batch-not-secured-source.kamelet.yaml, kamelets/kafka-batch-scram-source.kamelet.yaml, kamelets/kafka-batch-source.kamelet.yaml, kamelets/kafka-batch-ssl-source.kamelet.yaml, kamelets/spring-rabbitmq-sink.kamelet.yaml, kamelets/spring-rabbitmq-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jms-pooled-apache-artemis-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jms-pooled-apache-artemis-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-apicurio-registry-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-apicurio-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-not-secured-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-scram-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-ssl-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/spring-rabbitmq-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/spring-rabbitmq-source.kamelet.yaml
=> JSON Schema int type seems not right

kamelets/spring-rabbitmq-sink.kamelet.yaml, kamelets/spring-rabbitmq-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/spring-rabbitmq-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/spring-rabbitmq-source.kamelet.yaml
=> Support TLS on RabbitMQ Kamelets 

library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, pom.xml
=> Upgrade Camel to version 4.12.0

kamelets/freemarker-template-action.kamelet.yaml, kamelets/jolt-transformation-action.kamelet.yaml, kamelets/jslt-action.kamelet.yaml, kamelets/json-patch-action.kamelet.yaml, kamelets/json-schema-validator-action.kamelet.yaml, kamelets/jsonata-action.kamelet.yaml, kamelets/mustache-template-action.kamelet.yaml, kamelets/mvel-template-action.kamelet.yaml, kamelets/rest-openapi-sink.kamelet.yaml, kamelets/sftp-sink.kamelet.yaml, kamelets/sftp-source.kamelet.yaml, kamelets/string-template-action.kamelet.yaml, kamelets/velocity-template-action.kamelet.yaml, kamelets/xj-template-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/freemarker-template-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jolt-transformation-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jslt-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/json-patch-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/json-schema-validator-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/jsonata-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mustache-template-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/mvel-template-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/rest-openapi-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sftp-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/sftp-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/string-template-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/velocity-template-action.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/xj-template-action.kamelet.yaml
=> Add ref and bean to the pattern for ResourceUri

kamelets/kafka-azure-schema-registry-sink.kamelet.yaml, kamelets/kafka-azure-schema-registry-source.kamelet.yaml, kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-azure-schema-registry-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-azure-schema-registry-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/kafka-batch-azure-schema-registry-source.kamelet.yaml, pom.xml
=> Align Azure Kafka related deps version to Azure SDK BOM version 1.2.36 for next Release 4.13.0

library/camel-kamelets-catalog/src/test/java/org/apache/camel/kamelets/catalog/KameletsCatalogTest.java, pom.xml
=> Upgrade to Camel 4.13.0

docs/modules/ROOT/partials/bitcoin-source-description.adoc, kamelets/bitcoin-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/bitcoin-source.kamelet.yaml
=> Kamelets Catalog - Make the description a one liner - Bitcoin source

docs/modules/ROOT/partials/ceph-sink-description.adoc, docs/modules/ROOT/partials/ceph-source-description.adoc, kamelets/ceph-sink.kamelet.yaml, kamelets/ceph-source.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ceph-sink.kamelet.yaml, library/camel-kamelets/src/main/resources/kamelets/ceph-source.kamelet.yaml
=> Kamelets Catalog - Make description a one liner - Ceph Kamelets

pom.xml, tests/camel-kamelets-itest/README.md, tests/camel-kamelets-itest/jbang.properties, tests/camel-kamelets-itest/src/test/java/AvroIT.java, tests/camel-kamelets-itest/src/test/java/KafkaIT.java, tests/camel-kamelets-itest/src/test/java/ProtobufIT.java, tests/camel-kamelets-itest/src/test/java/SlackIT.java, tests/camel-kamelets-itest/src/test/resources/citrus-application.properties, tests/camel-kamelets-itest/src/test/resources/junit-platform.properties, tests/camel-kamelets-itest/src/test/resources/kafka/kafka-router-pipe.it.yaml, tests/camel-kamelets-itest/src/test/resources/kafka/kafka-sink-pipe.it.yaml, tests/camel-kamelets-itest/src/test/resources/kafka/kafka-source-pipe.it.yaml, tests/camel-kamelets-itest/src/test/resources/slack/application.properties, tests/camel-kamelets-itest/src/test/resources/slack/slack-sink-pipe.it.yaml, tests/camel-kamelets-itest/src/test/resources/slack/slack-source-pipe.it.yaml
- Fix tests to use Camel 4.14.0
- Improve and stabilize integration tests
- Update to Citrus 4.8.0
=> [BACKPORT-4.14.x] chore: Fix integration tests

tests/camel-kamelets-itest/src/test/resources/aws/eventbridge/setupEventBridge.groovy
- Use fresh SQS client instance
- Avoid SQS connection problems when connecting to cached LocalStack container instance (from previous test) which is stopped already
Fixes #2595
=> fix(#2595): Workaround to fix AWS tests

tests/camel-kamelets-itest/pom.xml
Use the camel bom import for camel dependencies.
=> Use camel-bom for versions of camel dependencies
